---
- hosts: back
  tasks:
    - name: Ensure backend folder exists
      file:
        path: /home/{{ ansible_user }}/backend
        state: directory

    - name: Pull latest code and switch to deploy branch
      git:
        repo: "https://github.com/go-park-mail-ru/2025_2_Suzuki_plus_one.git"
        dest: /home/{{ ansible_user }}/backend
        update: yes
        version: deploy

    - name: Build and start backend containers
      shell: |
        cd /home/{{ ansible_user }}/backend
        make all-bootstrap

    - name: Wait for server to start
      uri:
        url: "http://217.16.18.125/api/v1/movie/recommendations?limit=1"
        status_code: 200
        timeout: 10
        validate_certs: no
      register: server_health
      retries: 3
      delay: 3
      until: server_health.status == 200
