#!/bin/bash

# Run all pre-commit hooks in the pre-commit.d directory

HOOK_DIR="$(dirname "$0")/pre-commit.d"

if [ -d "$HOOK_DIR" ]; then
	for hook in "$HOOK_DIR"/*; do
		if [ -x "$hook" ]; then
			"$hook"
			status=$?
			if [ $status -ne 0 ]; then
				echo "pre-commit hook $hook failed with status $status"
				exit $status
			fi
		fi
	done
fi