// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./contract_mock.go -package=controller
//

// Package controller is a generated GoMock package.
package controller

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2025_2_Suzuki_plus_one/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockGetMoviesUsecase is a mock of GetMoviesUsecase interface.
type MockGetMoviesUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetMoviesUsecaseMockRecorder
	isgomock struct{}
}

// MockGetMoviesUsecaseMockRecorder is the mock recorder for MockGetMoviesUsecase.
type MockGetMoviesUsecaseMockRecorder struct {
	mock *MockGetMoviesUsecase
}

// NewMockGetMoviesUsecase creates a new mock instance.
func NewMockGetMoviesUsecase(ctrl *gomock.Controller) *MockGetMoviesUsecase {
	mock := &MockGetMoviesUsecase{ctrl: ctrl}
	mock.recorder = &MockGetMoviesUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetMoviesUsecase) EXPECT() *MockGetMoviesUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetMoviesUsecase) Execute(arg0 context.Context, arg1 dto.GetMoviesInput) (dto.GetMoviesOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetMoviesOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetMoviesUsecaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetMoviesUsecase)(nil).Execute), arg0, arg1)
}
