// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./contract_mock.go -package=controller
//

// Package controller is a generated GoMock package.
package controller

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2025_2_Suzuki_plus_one/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockGetMovieRecommendationsUsecase is a mock of GetMovieRecommendationsUsecase interface.
type MockGetMovieRecommendationsUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetMovieRecommendationsUsecaseMockRecorder
	isgomock struct{}
}

// MockGetMovieRecommendationsUsecaseMockRecorder is the mock recorder for MockGetMovieRecommendationsUsecase.
type MockGetMovieRecommendationsUsecaseMockRecorder struct {
	mock *MockGetMovieRecommendationsUsecase
}

// NewMockGetMovieRecommendationsUsecase creates a new mock instance.
func NewMockGetMovieRecommendationsUsecase(ctrl *gomock.Controller) *MockGetMovieRecommendationsUsecase {
	mock := &MockGetMovieRecommendationsUsecase{ctrl: ctrl}
	mock.recorder = &MockGetMovieRecommendationsUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetMovieRecommendationsUsecase) EXPECT() *MockGetMovieRecommendationsUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetMovieRecommendationsUsecase) Execute(arg0 context.Context, arg1 dto.GetMovieRecommendationsInput) (dto.GetMovieRecommendationsOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetMovieRecommendationsOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetMovieRecommendationsUsecaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetMovieRecommendationsUsecase)(nil).Execute), arg0, arg1)
}

// MockGetObjectUsecase is a mock of GetObjectUsecase interface.
type MockGetObjectUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetObjectUsecaseMockRecorder
	isgomock struct{}
}

// MockGetObjectUsecaseMockRecorder is the mock recorder for MockGetObjectUsecase.
type MockGetObjectUsecaseMockRecorder struct {
	mock *MockGetObjectUsecase
}

// NewMockGetObjectUsecase creates a new mock instance.
func NewMockGetObjectUsecase(ctrl *gomock.Controller) *MockGetObjectUsecase {
	mock := &MockGetObjectUsecase{ctrl: ctrl}
	mock.recorder = &MockGetObjectUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetObjectUsecase) EXPECT() *MockGetObjectUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetObjectUsecase) Execute(arg0 context.Context, arg1 dto.GetObjectInput) (dto.GetObjectOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetObjectOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetObjectUsecaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetObjectUsecase)(nil).Execute), arg0, arg1)
}

// MockPostAuthSignInUsecase is a mock of PostAuthSignInUsecase interface.
type MockPostAuthSignInUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockPostAuthSignInUsecaseMockRecorder
	isgomock struct{}
}

// MockPostAuthSignInUsecaseMockRecorder is the mock recorder for MockPostAuthSignInUsecase.
type MockPostAuthSignInUsecaseMockRecorder struct {
	mock *MockPostAuthSignInUsecase
}

// NewMockPostAuthSignInUsecase creates a new mock instance.
func NewMockPostAuthSignInUsecase(ctrl *gomock.Controller) *MockPostAuthSignInUsecase {
	mock := &MockPostAuthSignInUsecase{ctrl: ctrl}
	mock.recorder = &MockPostAuthSignInUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostAuthSignInUsecase) EXPECT() *MockPostAuthSignInUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockPostAuthSignInUsecase) Execute(arg0 context.Context, arg1 dto.PostAuthSignInInput) (dto.PostAuthSignInOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.PostAuthSignInOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockPostAuthSignInUsecaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockPostAuthSignInUsecase)(nil).Execute), arg0, arg1)
}
