// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./mocks/contract_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/go-park-mail-ru/2025_2_Suzuki_plus_one/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRepository)(nil).Close))
}

// Connect mocks base method.
func (m *MockRepository) Connect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockRepositoryMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockRepository)(nil).Connect))
}

// MockMediaRepository is a mock of MediaRepository interface.
type MockMediaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMediaRepositoryMockRecorder
	isgomock struct{}
}

// MockMediaRepositoryMockRecorder is the mock recorder for MockMediaRepository.
type MockMediaRepositoryMockRecorder struct {
	mock *MockMediaRepository
}

// NewMockMediaRepository creates a new mock instance.
func NewMockMediaRepository(ctrl *gomock.Controller) *MockMediaRepository {
	mock := &MockMediaRepository{ctrl: ctrl}
	mock.recorder = &MockMediaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaRepository) EXPECT() *MockMediaRepositoryMockRecorder {
	return m.recorder
}

// GetMediaByID mocks base method.
func (m *MockMediaRepository) GetMediaByID(ctx context.Context, media_id uint) (*entity.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaByID", ctx, media_id)
	ret0, _ := ret[0].(*entity.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaByID indicates an expected call of GetMediaByID.
func (mr *MockMediaRepositoryMockRecorder) GetMediaByID(ctx, media_id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaByID", reflect.TypeOf((*MockMediaRepository)(nil).GetMediaByID), ctx, media_id)
}

// GetMediaCount mocks base method.
func (m *MockMediaRepository) GetMediaCount(ctx context.Context, media_type string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaCount", ctx, media_type)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaCount indicates an expected call of GetMediaCount.
func (mr *MockMediaRepositoryMockRecorder) GetMediaCount(ctx, media_type any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaCount", reflect.TypeOf((*MockMediaRepository)(nil).GetMediaCount), ctx, media_type)
}

// GetMediaGenres mocks base method.
func (m *MockMediaRepository) GetMediaGenres(ctx context.Context, media_id uint) ([]entity.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaGenres", ctx, media_id)
	ret0, _ := ret[0].([]entity.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaGenres indicates an expected call of GetMediaGenres.
func (mr *MockMediaRepositoryMockRecorder) GetMediaGenres(ctx, media_id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaGenres", reflect.TypeOf((*MockMediaRepository)(nil).GetMediaGenres), ctx, media_id)
}

// GetMediaPostersKeys mocks base method.
func (m *MockMediaRepository) GetMediaPostersKeys(ctx context.Context, media_id uint) ([]entity.S3Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaPostersKeys", ctx, media_id)
	ret0, _ := ret[0].([]entity.S3Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaPostersKeys indicates an expected call of GetMediaPostersKeys.
func (mr *MockMediaRepositoryMockRecorder) GetMediaPostersKeys(ctx, media_id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaPostersKeys", reflect.TypeOf((*MockMediaRepository)(nil).GetMediaPostersKeys), ctx, media_id)
}

// GetMediaSortedByName mocks base method.
func (m *MockMediaRepository) GetMediaSortedByName(ctx context.Context, limit, offset uint, media_type string) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaSortedByName", ctx, limit, offset, media_type)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaSortedByName indicates an expected call of GetMediaSortedByName.
func (mr *MockMediaRepositoryMockRecorder) GetMediaSortedByName(ctx, limit, offset, media_type any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaSortedByName", reflect.TypeOf((*MockMediaRepository)(nil).GetMediaSortedByName), ctx, limit, offset, media_type)
}

// GetMediaTrailersKeys mocks base method.
func (m *MockMediaRepository) GetMediaTrailersKeys(ctx context.Context, media_id uint) ([]entity.S3Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaTrailersKeys", ctx, media_id)
	ret0, _ := ret[0].([]entity.S3Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaTrailersKeys indicates an expected call of GetMediaTrailersKeys.
func (mr *MockMediaRepositoryMockRecorder) GetMediaTrailersKeys(ctx, media_id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaTrailersKeys", reflect.TypeOf((*MockMediaRepository)(nil).GetMediaTrailersKeys), ctx, media_id)
}

// GetMediaWatchKey mocks base method.
func (m *MockMediaRepository) GetMediaWatchKey(ctx context.Context, media_id uint) (*entity.S3Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaWatchKey", ctx, media_id)
	ret0, _ := ret[0].(*entity.S3Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaWatchKey indicates an expected call of GetMediaWatchKey.
func (mr *MockMediaRepositoryMockRecorder) GetMediaWatchKey(ctx, media_id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaWatchKey", reflect.TypeOf((*MockMediaRepository)(nil).GetMediaWatchKey), ctx, media_id)
}

// MockActorRepository is a mock of ActorRepository interface.
type MockActorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockActorRepositoryMockRecorder
	isgomock struct{}
}

// MockActorRepositoryMockRecorder is the mock recorder for MockActorRepository.
type MockActorRepositoryMockRecorder struct {
	mock *MockActorRepository
}

// NewMockActorRepository creates a new mock instance.
func NewMockActorRepository(ctrl *gomock.Controller) *MockActorRepository {
	mock := &MockActorRepository{ctrl: ctrl}
	mock.recorder = &MockActorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActorRepository) EXPECT() *MockActorRepositoryMockRecorder {
	return m.recorder
}

// GetActorByID mocks base method.
func (m *MockActorRepository) GetActorByID(ctx context.Context, actorID uint) (*entity.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorByID", ctx, actorID)
	ret0, _ := ret[0].(*entity.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActorByID indicates an expected call of GetActorByID.
func (mr *MockActorRepositoryMockRecorder) GetActorByID(ctx, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorByID", reflect.TypeOf((*MockActorRepository)(nil).GetActorByID), ctx, actorID)
}

// GetActorImageS3 mocks base method.
func (m *MockActorRepository) GetActorImageS3(ctx context.Context, actorID uint) ([]entity.S3Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorImageS3", ctx, actorID)
	ret0, _ := ret[0].([]entity.S3Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActorImageS3 indicates an expected call of GetActorImageS3.
func (mr *MockActorRepositoryMockRecorder) GetActorImageS3(ctx, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorImageS3", reflect.TypeOf((*MockActorRepository)(nil).GetActorImageS3), ctx, actorID)
}

// GetActorsByMediaID mocks base method.
func (m *MockActorRepository) GetActorsByMediaID(ctx context.Context, media_id uint) ([]entity.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorsByMediaID", ctx, media_id)
	ret0, _ := ret[0].([]entity.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActorsByMediaID indicates an expected call of GetActorsByMediaID.
func (mr *MockActorRepositoryMockRecorder) GetActorsByMediaID(ctx, media_id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorsByMediaID", reflect.TypeOf((*MockActorRepository)(nil).GetActorsByMediaID), ctx, media_id)
}

// GetMediasByActorID mocks base method.
func (m *MockActorRepository) GetMediasByActorID(ctx context.Context, actorID uint) ([]entity.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediasByActorID", ctx, actorID)
	ret0, _ := ret[0].([]entity.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediasByActorID indicates an expected call of GetMediasByActorID.
func (mr *MockActorRepositoryMockRecorder) GetMediasByActorID(ctx, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediasByActorID", reflect.TypeOf((*MockActorRepository)(nil).GetMediasByActorID), ctx, actorID)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(ctx context.Context, user entity.User) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), ctx, user)
}

// GetUserAvatarKey mocks base method.
func (m *MockUserRepository) GetUserAvatarKey(ctx context.Context, userID uint) (*entity.S3Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAvatarKey", ctx, userID)
	ret0, _ := ret[0].(*entity.S3Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAvatarKey indicates an expected call of GetUserAvatarKey.
func (mr *MockUserRepositoryMockRecorder) GetUserAvatarKey(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAvatarKey", reflect.TypeOf((*MockUserRepository)(nil).GetUserAvatarKey), ctx, userID)
}

// GetUserByEmail mocks base method.
func (m *MockUserRepository) GetUserByEmail(ctx context.Context, email string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserRepositoryMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockUserRepository) GetUserByID(ctx context.Context, userID uint) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositoryMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepository)(nil).GetUserByID), ctx, userID)
}

// UpdateUser mocks base method.
func (m *MockUserRepository) UpdateUser(ctx context.Context, userID uint, username, email, dateOfBirth, phoneNumber string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, userID, username, email, dateOfBirth, phoneNumber)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserRepositoryMockRecorder) UpdateUser(ctx, userID, username, email, dateOfBirth, phoneNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserRepository)(nil).UpdateUser), ctx, userID, username, email, dateOfBirth, phoneNumber)
}

// UpdateUserAvatarKey mocks base method.
func (m *MockUserRepository) UpdateUserAvatarKey(ctx context.Context, userID, assetImageID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserAvatarKey", ctx, userID, assetImageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserAvatarKey indicates an expected call of UpdateUserAvatarKey.
func (mr *MockUserRepositoryMockRecorder) UpdateUserAvatarKey(ctx, userID, assetImageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserAvatarKey", reflect.TypeOf((*MockUserRepository)(nil).UpdateUserAvatarKey), ctx, userID, assetImageID)
}

// UpdateUserPassword mocks base method.
func (m *MockUserRepository) UpdateUserPassword(ctx context.Context, userID uint, newHashedPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPassword", ctx, userID, newHashedPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPassword indicates an expected call of UpdateUserPassword.
func (mr *MockUserRepositoryMockRecorder) UpdateUserPassword(ctx, userID, newHashedPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPassword", reflect.TypeOf((*MockUserRepository)(nil).UpdateUserPassword), ctx, userID, newHashedPassword)
}

// MockAssetRepository is a mock of AssetRepository interface.
type MockAssetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAssetRepositoryMockRecorder
	isgomock struct{}
}

// MockAssetRepositoryMockRecorder is the mock recorder for MockAssetRepository.
type MockAssetRepositoryMockRecorder struct {
	mock *MockAssetRepository
}

// NewMockAssetRepository creates a new mock instance.
func NewMockAssetRepository(ctrl *gomock.Controller) *MockAssetRepository {
	mock := &MockAssetRepository{ctrl: ctrl}
	mock.recorder = &MockAssetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssetRepository) EXPECT() *MockAssetRepositoryMockRecorder {
	return m.recorder
}

// CreateAsset mocks base method.
func (m *MockAssetRepository) CreateAsset(ctx context.Context, asset entity.Asset) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAsset", ctx, asset)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAsset indicates an expected call of CreateAsset.
func (mr *MockAssetRepositoryMockRecorder) CreateAsset(ctx, asset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAsset", reflect.TypeOf((*MockAssetRepository)(nil).CreateAsset), ctx, asset)
}

// CreateAssetImage mocks base method.
func (m *MockAssetRepository) CreateAssetImage(ctx context.Context, assetImage entity.AssetImage) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAssetImage", ctx, assetImage)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAssetImage indicates an expected call of CreateAssetImage.
func (mr *MockAssetRepositoryMockRecorder) CreateAssetImage(ctx, assetImage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAssetImage", reflect.TypeOf((*MockAssetRepository)(nil).CreateAssetImage), ctx, assetImage)
}

// GetAssetByID mocks base method.
func (m *MockAssetRepository) GetAssetByID(ctx context.Context, assetID uint) (*entity.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssetByID", ctx, assetID)
	ret0, _ := ret[0].(*entity.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssetByID indicates an expected call of GetAssetByID.
func (mr *MockAssetRepositoryMockRecorder) GetAssetByID(ctx, assetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssetByID", reflect.TypeOf((*MockAssetRepository)(nil).GetAssetByID), ctx, assetID)
}

// GetAssetImageByID mocks base method.
func (m *MockAssetRepository) GetAssetImageByID(ctx context.Context, assetImageID uint) (*entity.AssetImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssetImageByID", ctx, assetImageID)
	ret0, _ := ret[0].(*entity.AssetImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssetImageByID indicates an expected call of GetAssetImageByID.
func (mr *MockAssetRepositoryMockRecorder) GetAssetImageByID(ctx, assetImageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssetImageByID", reflect.TypeOf((*MockAssetRepository)(nil).GetAssetImageByID), ctx, assetImageID)
}

// MockTokenRepository is a mock of TokenRepository interface.
type MockTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockTokenRepositoryMockRecorder is the mock recorder for MockTokenRepository.
type MockTokenRepositoryMockRecorder struct {
	mock *MockTokenRepository
}

// NewMockTokenRepository creates a new mock instance.
func NewMockTokenRepository(ctrl *gomock.Controller) *MockTokenRepository {
	mock := &MockTokenRepository{ctrl: ctrl}
	mock.recorder = &MockTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRepository) EXPECT() *MockTokenRepositoryMockRecorder {
	return m.recorder
}

// AddNewRefreshToken mocks base method.
func (m *MockTokenRepository) AddNewRefreshToken(ctx context.Context, userID uint, refreshToken string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewRefreshToken", ctx, userID, refreshToken, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNewRefreshToken indicates an expected call of AddNewRefreshToken.
func (mr *MockTokenRepositoryMockRecorder) AddNewRefreshToken(ctx, userID, refreshToken, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewRefreshToken", reflect.TypeOf((*MockTokenRepository)(nil).AddNewRefreshToken), ctx, userID, refreshToken, expiresAt)
}

// GetRefreshTokensForUser mocks base method.
func (m *MockTokenRepository) GetRefreshTokensForUser(ctx context.Context, userID uint) ([]entity.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokensForUser", ctx, userID)
	ret0, _ := ret[0].([]entity.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshTokensForUser indicates an expected call of GetRefreshTokensForUser.
func (mr *MockTokenRepositoryMockRecorder) GetRefreshTokensForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokensForUser", reflect.TypeOf((*MockTokenRepository)(nil).GetRefreshTokensForUser), ctx, userID)
}

// RemoveRefreshToken mocks base method.
func (m *MockTokenRepository) RemoveRefreshToken(ctx context.Context, userID uint, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRefreshToken", ctx, userID, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRefreshToken indicates an expected call of RemoveRefreshToken.
func (mr *MockTokenRepositoryMockRecorder) RemoveRefreshToken(ctx, userID, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRefreshToken", reflect.TypeOf((*MockTokenRepository)(nil).RemoveRefreshToken), ctx, userID, refreshToken)
}

// MockS3 is a mock of S3 interface.
type MockS3 struct {
	ctrl     *gomock.Controller
	recorder *MockS3MockRecorder
	isgomock struct{}
}

// MockS3MockRecorder is the mock recorder for MockS3.
type MockS3MockRecorder struct {
	mock *MockS3
}

// NewMockS3 creates a new mock instance.
func NewMockS3(ctrl *gomock.Controller) *MockS3 {
	mock := &MockS3{ctrl: ctrl}
	mock.recorder = &MockS3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3) EXPECT() *MockS3MockRecorder {
	return m.recorder
}

// MockObjectRepository is a mock of ObjectRepository interface.
type MockObjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockObjectRepositoryMockRecorder
	isgomock struct{}
}

// MockObjectRepositoryMockRecorder is the mock recorder for MockObjectRepository.
type MockObjectRepositoryMockRecorder struct {
	mock *MockObjectRepository
}

// NewMockObjectRepository creates a new mock instance.
func NewMockObjectRepository(ctrl *gomock.Controller) *MockObjectRepository {
	mock := &MockObjectRepository{ctrl: ctrl}
	mock.recorder = &MockObjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectRepository) EXPECT() *MockObjectRepositoryMockRecorder {
	return m.recorder
}

// DeleteObject mocks base method.
func (m *MockObjectRepository) DeleteObject(ctx context.Context, bucketName, objectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, bucketName, objectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockObjectRepositoryMockRecorder) DeleteObject(ctx, bucketName, objectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockObjectRepository)(nil).DeleteObject), ctx, bucketName, objectName)
}

// GeneratePresignedURL mocks base method.
func (m *MockObjectRepository) GeneratePresignedURL(ctx context.Context, bucketName, objectName string, expiration time.Duration) (*entity.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePresignedURL", ctx, bucketName, objectName, expiration)
	ret0, _ := ret[0].(*entity.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePresignedURL indicates an expected call of GeneratePresignedURL.
func (mr *MockObjectRepositoryMockRecorder) GeneratePresignedURL(ctx, bucketName, objectName, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePresignedURL", reflect.TypeOf((*MockObjectRepository)(nil).GeneratePresignedURL), ctx, bucketName, objectName, expiration)
}

// GeneratePublicURL mocks base method.
func (m *MockObjectRepository) GeneratePublicURL(ctx context.Context, bucketName, objectName string) (*entity.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePublicURL", ctx, bucketName, objectName)
	ret0, _ := ret[0].(*entity.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePublicURL indicates an expected call of GeneratePublicURL.
func (mr *MockObjectRepositoryMockRecorder) GeneratePublicURL(ctx, bucketName, objectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePublicURL", reflect.TypeOf((*MockObjectRepository)(nil).GeneratePublicURL), ctx, bucketName, objectName)
}

// UploadObject mocks base method.
func (m *MockObjectRepository) UploadObject(ctx context.Context, bucketName, objectName, mimeType string, data []byte) (*entity.S3Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadObject", ctx, bucketName, objectName, mimeType, data)
	ret0, _ := ret[0].(*entity.S3Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadObject indicates an expected call of UploadObject.
func (mr *MockObjectRepositoryMockRecorder) UploadObject(ctx, bucketName, objectName, mimeType, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadObject", reflect.TypeOf((*MockObjectRepository)(nil).UploadObject), ctx, bucketName, objectName, mimeType, data)
}

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// AddSession mocks base method.
func (m *MockSessionRepository) AddSession(ctx context.Context, userID uint, accessToken string, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSession", ctx, userID, accessToken, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSession indicates an expected call of AddSession.
func (mr *MockSessionRepositoryMockRecorder) AddSession(ctx, userID, accessToken, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSession", reflect.TypeOf((*MockSessionRepository)(nil).AddSession), ctx, userID, accessToken, expiration)
}

// DeleteSession mocks base method.
func (m *MockSessionRepository) DeleteSession(ctx context.Context, userID uint, accessToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, userID, accessToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockSessionRepositoryMockRecorder) DeleteSession(ctx, userID, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockSessionRepository)(nil).DeleteSession), ctx, userID, accessToken)
}

// GetUserIDByAccessToken mocks base method.
func (m *MockSessionRepository) GetUserIDByAccessToken(ctx context.Context, accessToken string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDByAccessToken", ctx, accessToken)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDByAccessToken indicates an expected call of GetUserIDByAccessToken.
func (mr *MockSessionRepositoryMockRecorder) GetUserIDByAccessToken(ctx, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDByAccessToken", reflect.TypeOf((*MockSessionRepository)(nil).GetUserIDByAccessToken), ctx, accessToken)
}
