// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./mocks/contract_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2025_2_Suzuki_plus_one/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockGetMediaRecommendationsUseCase is a mock of GetMediaRecommendationsUseCase interface.
type MockGetMediaRecommendationsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetMediaRecommendationsUseCaseMockRecorder
	isgomock struct{}
}

// MockGetMediaRecommendationsUseCaseMockRecorder is the mock recorder for MockGetMediaRecommendationsUseCase.
type MockGetMediaRecommendationsUseCaseMockRecorder struct {
	mock *MockGetMediaRecommendationsUseCase
}

// NewMockGetMediaRecommendationsUseCase creates a new mock instance.
func NewMockGetMediaRecommendationsUseCase(ctrl *gomock.Controller) *MockGetMediaRecommendationsUseCase {
	mock := &MockGetMediaRecommendationsUseCase{ctrl: ctrl}
	mock.recorder = &MockGetMediaRecommendationsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetMediaRecommendationsUseCase) EXPECT() *MockGetMediaRecommendationsUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetMediaRecommendationsUseCase) Execute(arg0 context.Context, arg1 dto.GetMediaRecommendationsInput) (dto.GetMediaRecommendationsOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetMediaRecommendationsOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetMediaRecommendationsUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetMediaRecommendationsUseCase)(nil).Execute), arg0, arg1)
}

// MockGetObjectUseCase is a mock of GetObjectUseCase interface.
type MockGetObjectUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetObjectUseCaseMockRecorder
	isgomock struct{}
}

// MockGetObjectUseCaseMockRecorder is the mock recorder for MockGetObjectUseCase.
type MockGetObjectUseCaseMockRecorder struct {
	mock *MockGetObjectUseCase
}

// NewMockGetObjectUseCase creates a new mock instance.
func NewMockGetObjectUseCase(ctrl *gomock.Controller) *MockGetObjectUseCase {
	mock := &MockGetObjectUseCase{ctrl: ctrl}
	mock.recorder = &MockGetObjectUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetObjectUseCase) EXPECT() *MockGetObjectUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetObjectUseCase) Execute(arg0 context.Context, arg1 dto.GetObjectInput) (dto.GetObjectOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetObjectOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetObjectUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetObjectUseCase)(nil).Execute), arg0, arg1)
}

// MockPostAuthSignInUseCase is a mock of PostAuthSignInUseCase interface.
type MockPostAuthSignInUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPostAuthSignInUseCaseMockRecorder
	isgomock struct{}
}

// MockPostAuthSignInUseCaseMockRecorder is the mock recorder for MockPostAuthSignInUseCase.
type MockPostAuthSignInUseCaseMockRecorder struct {
	mock *MockPostAuthSignInUseCase
}

// NewMockPostAuthSignInUseCase creates a new mock instance.
func NewMockPostAuthSignInUseCase(ctrl *gomock.Controller) *MockPostAuthSignInUseCase {
	mock := &MockPostAuthSignInUseCase{ctrl: ctrl}
	mock.recorder = &MockPostAuthSignInUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostAuthSignInUseCase) EXPECT() *MockPostAuthSignInUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockPostAuthSignInUseCase) Execute(arg0 context.Context, arg1 dto.PostAuthSignInInput) (dto.PostAuthSignInOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.PostAuthSignInOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockPostAuthSignInUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockPostAuthSignInUseCase)(nil).Execute), arg0, arg1)
}

// MockGetAuthRefreshUseCase is a mock of GetAuthRefreshUseCase interface.
type MockGetAuthRefreshUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetAuthRefreshUseCaseMockRecorder
	isgomock struct{}
}

// MockGetAuthRefreshUseCaseMockRecorder is the mock recorder for MockGetAuthRefreshUseCase.
type MockGetAuthRefreshUseCaseMockRecorder struct {
	mock *MockGetAuthRefreshUseCase
}

// NewMockGetAuthRefreshUseCase creates a new mock instance.
func NewMockGetAuthRefreshUseCase(ctrl *gomock.Controller) *MockGetAuthRefreshUseCase {
	mock := &MockGetAuthRefreshUseCase{ctrl: ctrl}
	mock.recorder = &MockGetAuthRefreshUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetAuthRefreshUseCase) EXPECT() *MockGetAuthRefreshUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetAuthRefreshUseCase) Execute(arg0 context.Context, arg1 dto.GetAuthRefreshInput) (dto.GetAuthRefreshOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetAuthRefreshOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetAuthRefreshUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetAuthRefreshUseCase)(nil).Execute), arg0, arg1)
}

// MockPostAuthSignUpUseCase is a mock of PostAuthSignUpUseCase interface.
type MockPostAuthSignUpUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPostAuthSignUpUseCaseMockRecorder
	isgomock struct{}
}

// MockPostAuthSignUpUseCaseMockRecorder is the mock recorder for MockPostAuthSignUpUseCase.
type MockPostAuthSignUpUseCaseMockRecorder struct {
	mock *MockPostAuthSignUpUseCase
}

// NewMockPostAuthSignUpUseCase creates a new mock instance.
func NewMockPostAuthSignUpUseCase(ctrl *gomock.Controller) *MockPostAuthSignUpUseCase {
	mock := &MockPostAuthSignUpUseCase{ctrl: ctrl}
	mock.recorder = &MockPostAuthSignUpUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostAuthSignUpUseCase) EXPECT() *MockPostAuthSignUpUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockPostAuthSignUpUseCase) Execute(arg0 context.Context, arg1 dto.PostAuthSignUpInput) (dto.PostAuthSignUpOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.PostAuthSignUpOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockPostAuthSignUpUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockPostAuthSignUpUseCase)(nil).Execute), arg0, arg1)
}

// MockGetAuthSignOutUseCase is a mock of GetAuthSignOutUseCase interface.
type MockGetAuthSignOutUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetAuthSignOutUseCaseMockRecorder
	isgomock struct{}
}

// MockGetAuthSignOutUseCaseMockRecorder is the mock recorder for MockGetAuthSignOutUseCase.
type MockGetAuthSignOutUseCaseMockRecorder struct {
	mock *MockGetAuthSignOutUseCase
}

// NewMockGetAuthSignOutUseCase creates a new mock instance.
func NewMockGetAuthSignOutUseCase(ctrl *gomock.Controller) *MockGetAuthSignOutUseCase {
	mock := &MockGetAuthSignOutUseCase{ctrl: ctrl}
	mock.recorder = &MockGetAuthSignOutUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetAuthSignOutUseCase) EXPECT() *MockGetAuthSignOutUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetAuthSignOutUseCase) Execute(arg0 context.Context, arg1 dto.GetAuthSignOutInput) (dto.GetAuthSignOutOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetAuthSignOutOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetAuthSignOutUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetAuthSignOutUseCase)(nil).Execute), arg0, arg1)
}

// MockGetUserMeUseCase is a mock of GetUserMeUseCase interface.
type MockGetUserMeUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetUserMeUseCaseMockRecorder
	isgomock struct{}
}

// MockGetUserMeUseCaseMockRecorder is the mock recorder for MockGetUserMeUseCase.
type MockGetUserMeUseCaseMockRecorder struct {
	mock *MockGetUserMeUseCase
}

// NewMockGetUserMeUseCase creates a new mock instance.
func NewMockGetUserMeUseCase(ctrl *gomock.Controller) *MockGetUserMeUseCase {
	mock := &MockGetUserMeUseCase{ctrl: ctrl}
	mock.recorder = &MockGetUserMeUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetUserMeUseCase) EXPECT() *MockGetUserMeUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetUserMeUseCase) Execute(arg0 context.Context, arg1 dto.GetUserMeInput) (dto.GetUserMeOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetUserMeOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetUserMeUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetUserMeUseCase)(nil).Execute), arg0, arg1)
}

// MockGetActorUseCase is a mock of GetActorUseCase interface.
type MockGetActorUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetActorUseCaseMockRecorder
	isgomock struct{}
}

// MockGetActorUseCaseMockRecorder is the mock recorder for MockGetActorUseCase.
type MockGetActorUseCaseMockRecorder struct {
	mock *MockGetActorUseCase
}

// NewMockGetActorUseCase creates a new mock instance.
func NewMockGetActorUseCase(ctrl *gomock.Controller) *MockGetActorUseCase {
	mock := &MockGetActorUseCase{ctrl: ctrl}
	mock.recorder = &MockGetActorUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetActorUseCase) EXPECT() *MockGetActorUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetActorUseCase) Execute(arg0 context.Context, arg1 dto.GetActorInput) (dto.GetActorOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetActorOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetActorUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetActorUseCase)(nil).Execute), arg0, arg1)
}

// MockGetMediaUseCase is a mock of GetMediaUseCase interface.
type MockGetMediaUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetMediaUseCaseMockRecorder
	isgomock struct{}
}

// MockGetMediaUseCaseMockRecorder is the mock recorder for MockGetMediaUseCase.
type MockGetMediaUseCaseMockRecorder struct {
	mock *MockGetMediaUseCase
}

// NewMockGetMediaUseCase creates a new mock instance.
func NewMockGetMediaUseCase(ctrl *gomock.Controller) *MockGetMediaUseCase {
	mock := &MockGetMediaUseCase{ctrl: ctrl}
	mock.recorder = &MockGetMediaUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetMediaUseCase) EXPECT() *MockGetMediaUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetMediaUseCase) Execute(arg0 context.Context, arg1 dto.GetMediaInput) (dto.GetMediaOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetMediaOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetMediaUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetMediaUseCase)(nil).Execute), arg0, arg1)
}

// MockGetMediaWatchUseCase is a mock of GetMediaWatchUseCase interface.
type MockGetMediaWatchUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetMediaWatchUseCaseMockRecorder
	isgomock struct{}
}

// MockGetMediaWatchUseCaseMockRecorder is the mock recorder for MockGetMediaWatchUseCase.
type MockGetMediaWatchUseCaseMockRecorder struct {
	mock *MockGetMediaWatchUseCase
}

// NewMockGetMediaWatchUseCase creates a new mock instance.
func NewMockGetMediaWatchUseCase(ctrl *gomock.Controller) *MockGetMediaWatchUseCase {
	mock := &MockGetMediaWatchUseCase{ctrl: ctrl}
	mock.recorder = &MockGetMediaWatchUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetMediaWatchUseCase) EXPECT() *MockGetMediaWatchUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetMediaWatchUseCase) Execute(arg0 context.Context, arg1 dto.GetMediaWatchInput) (dto.GetMediaWatchOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetMediaWatchOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetMediaWatchUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetMediaWatchUseCase)(nil).Execute), arg0, arg1)
}

// MockPostUserMeUpdateUseCase is a mock of PostUserMeUpdateUseCase interface.
type MockPostUserMeUpdateUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPostUserMeUpdateUseCaseMockRecorder
	isgomock struct{}
}

// MockPostUserMeUpdateUseCaseMockRecorder is the mock recorder for MockPostUserMeUpdateUseCase.
type MockPostUserMeUpdateUseCaseMockRecorder struct {
	mock *MockPostUserMeUpdateUseCase
}

// NewMockPostUserMeUpdateUseCase creates a new mock instance.
func NewMockPostUserMeUpdateUseCase(ctrl *gomock.Controller) *MockPostUserMeUpdateUseCase {
	mock := &MockPostUserMeUpdateUseCase{ctrl: ctrl}
	mock.recorder = &MockPostUserMeUpdateUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostUserMeUpdateUseCase) EXPECT() *MockPostUserMeUpdateUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockPostUserMeUpdateUseCase) Execute(arg0 context.Context, arg1 dto.PostUserMeUpdateInput) (dto.PostUserMeUpdateOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.PostUserMeUpdateOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockPostUserMeUpdateUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockPostUserMeUpdateUseCase)(nil).Execute), arg0, arg1)
}

// MockPostUserMeUpdateAvatarUseCase is a mock of PostUserMeUpdateAvatarUseCase interface.
type MockPostUserMeUpdateAvatarUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPostUserMeUpdateAvatarUseCaseMockRecorder
	isgomock struct{}
}

// MockPostUserMeUpdateAvatarUseCaseMockRecorder is the mock recorder for MockPostUserMeUpdateAvatarUseCase.
type MockPostUserMeUpdateAvatarUseCaseMockRecorder struct {
	mock *MockPostUserMeUpdateAvatarUseCase
}

// NewMockPostUserMeUpdateAvatarUseCase creates a new mock instance.
func NewMockPostUserMeUpdateAvatarUseCase(ctrl *gomock.Controller) *MockPostUserMeUpdateAvatarUseCase {
	mock := &MockPostUserMeUpdateAvatarUseCase{ctrl: ctrl}
	mock.recorder = &MockPostUserMeUpdateAvatarUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostUserMeUpdateAvatarUseCase) EXPECT() *MockPostUserMeUpdateAvatarUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockPostUserMeUpdateAvatarUseCase) Execute(arg0 context.Context, arg1 dto.PostUserMeUpdateAvatarInput) (dto.PostUserMeUpdateAvatarOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.PostUserMeUpdateAvatarOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockPostUserMeUpdateAvatarUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockPostUserMeUpdateAvatarUseCase)(nil).Execute), arg0, arg1)
}

// MockGetActorMediaUseCase is a mock of GetActorMediaUseCase interface.
type MockGetActorMediaUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetActorMediaUseCaseMockRecorder
	isgomock struct{}
}

// MockGetActorMediaUseCaseMockRecorder is the mock recorder for MockGetActorMediaUseCase.
type MockGetActorMediaUseCaseMockRecorder struct {
	mock *MockGetActorMediaUseCase
}

// NewMockGetActorMediaUseCase creates a new mock instance.
func NewMockGetActorMediaUseCase(ctrl *gomock.Controller) *MockGetActorMediaUseCase {
	mock := &MockGetActorMediaUseCase{ctrl: ctrl}
	mock.recorder = &MockGetActorMediaUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetActorMediaUseCase) EXPECT() *MockGetActorMediaUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetActorMediaUseCase) Execute(arg0 context.Context, arg1 dto.GetActorMediaInput) (dto.GetActorMediaOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetActorMediaOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetActorMediaUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetActorMediaUseCase)(nil).Execute), arg0, arg1)
}

// MockGetMediaActorUseCase is a mock of GetMediaActorUseCase interface.
type MockGetMediaActorUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetMediaActorUseCaseMockRecorder
	isgomock struct{}
}

// MockGetMediaActorUseCaseMockRecorder is the mock recorder for MockGetMediaActorUseCase.
type MockGetMediaActorUseCaseMockRecorder struct {
	mock *MockGetMediaActorUseCase
}

// NewMockGetMediaActorUseCase creates a new mock instance.
func NewMockGetMediaActorUseCase(ctrl *gomock.Controller) *MockGetMediaActorUseCase {
	mock := &MockGetMediaActorUseCase{ctrl: ctrl}
	mock.recorder = &MockGetMediaActorUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetMediaActorUseCase) EXPECT() *MockGetMediaActorUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetMediaActorUseCase) Execute(arg0 context.Context, arg1 dto.GetMediaActorInput) (dto.GetMediaActorOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetMediaActorOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetMediaActorUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetMediaActorUseCase)(nil).Execute), arg0, arg1)
}

// MockPostUserMeUpdatePasswordUseCase is a mock of PostUserMeUpdatePasswordUseCase interface.
type MockPostUserMeUpdatePasswordUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPostUserMeUpdatePasswordUseCaseMockRecorder
	isgomock struct{}
}

// MockPostUserMeUpdatePasswordUseCaseMockRecorder is the mock recorder for MockPostUserMeUpdatePasswordUseCase.
type MockPostUserMeUpdatePasswordUseCaseMockRecorder struct {
	mock *MockPostUserMeUpdatePasswordUseCase
}

// NewMockPostUserMeUpdatePasswordUseCase creates a new mock instance.
func NewMockPostUserMeUpdatePasswordUseCase(ctrl *gomock.Controller) *MockPostUserMeUpdatePasswordUseCase {
	mock := &MockPostUserMeUpdatePasswordUseCase{ctrl: ctrl}
	mock.recorder = &MockPostUserMeUpdatePasswordUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostUserMeUpdatePasswordUseCase) EXPECT() *MockPostUserMeUpdatePasswordUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockPostUserMeUpdatePasswordUseCase) Execute(arg0 context.Context, arg1 dto.PostUserMeUpdatePasswordInput) (dto.PostUserMeUpdatePasswordOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.PostUserMeUpdatePasswordOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockPostUserMeUpdatePasswordUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockPostUserMeUpdatePasswordUseCase)(nil).Execute), arg0, arg1)
}

// MockGetAppealMyUseCase is a mock of GetAppealMyUseCase interface.
type MockGetAppealMyUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetAppealMyUseCaseMockRecorder
	isgomock struct{}
}

// MockGetAppealMyUseCaseMockRecorder is the mock recorder for MockGetAppealMyUseCase.
type MockGetAppealMyUseCaseMockRecorder struct {
	mock *MockGetAppealMyUseCase
}

// NewMockGetAppealMyUseCase creates a new mock instance.
func NewMockGetAppealMyUseCase(ctrl *gomock.Controller) *MockGetAppealMyUseCase {
	mock := &MockGetAppealMyUseCase{ctrl: ctrl}
	mock.recorder = &MockGetAppealMyUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetAppealMyUseCase) EXPECT() *MockGetAppealMyUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetAppealMyUseCase) Execute(arg0 context.Context, arg1 dto.GetAppealMyInput) (dto.GetAppealMyOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetAppealMyOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetAppealMyUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetAppealMyUseCase)(nil).Execute), arg0, arg1)
}

// MockPostAppealNewUseCase is a mock of PostAppealNewUseCase interface.
type MockPostAppealNewUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPostAppealNewUseCaseMockRecorder
	isgomock struct{}
}

// MockPostAppealNewUseCaseMockRecorder is the mock recorder for MockPostAppealNewUseCase.
type MockPostAppealNewUseCaseMockRecorder struct {
	mock *MockPostAppealNewUseCase
}

// NewMockPostAppealNewUseCase creates a new mock instance.
func NewMockPostAppealNewUseCase(ctrl *gomock.Controller) *MockPostAppealNewUseCase {
	mock := &MockPostAppealNewUseCase{ctrl: ctrl}
	mock.recorder = &MockPostAppealNewUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostAppealNewUseCase) EXPECT() *MockPostAppealNewUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockPostAppealNewUseCase) Execute(arg0 context.Context, arg1 dto.PostAppealNewInput) (dto.PostAppealNewOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.PostAppealNewOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockPostAppealNewUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockPostAppealNewUseCase)(nil).Execute), arg0, arg1)
}

// MockGetAppealUseCase is a mock of GetAppealUseCase interface.
type MockGetAppealUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetAppealUseCaseMockRecorder
	isgomock struct{}
}

// MockGetAppealUseCaseMockRecorder is the mock recorder for MockGetAppealUseCase.
type MockGetAppealUseCaseMockRecorder struct {
	mock *MockGetAppealUseCase
}

// NewMockGetAppealUseCase creates a new mock instance.
func NewMockGetAppealUseCase(ctrl *gomock.Controller) *MockGetAppealUseCase {
	mock := &MockGetAppealUseCase{ctrl: ctrl}
	mock.recorder = &MockGetAppealUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetAppealUseCase) EXPECT() *MockGetAppealUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetAppealUseCase) Execute(arg0 context.Context, arg1 dto.GetAppealInput) (dto.GetAppealOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetAppealOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetAppealUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetAppealUseCase)(nil).Execute), arg0, arg1)
}

// MockPutAppealResolveUseCase is a mock of PutAppealResolveUseCase interface.
type MockPutAppealResolveUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPutAppealResolveUseCaseMockRecorder
	isgomock struct{}
}

// MockPutAppealResolveUseCaseMockRecorder is the mock recorder for MockPutAppealResolveUseCase.
type MockPutAppealResolveUseCaseMockRecorder struct {
	mock *MockPutAppealResolveUseCase
}

// NewMockPutAppealResolveUseCase creates a new mock instance.
func NewMockPutAppealResolveUseCase(ctrl *gomock.Controller) *MockPutAppealResolveUseCase {
	mock := &MockPutAppealResolveUseCase{ctrl: ctrl}
	mock.recorder = &MockPutAppealResolveUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPutAppealResolveUseCase) EXPECT() *MockPutAppealResolveUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockPutAppealResolveUseCase) Execute(arg0 context.Context, arg1 dto.PutAppealResolveInput) (dto.PutAppealResolveOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.PutAppealResolveOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockPutAppealResolveUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockPutAppealResolveUseCase)(nil).Execute), arg0, arg1)
}

// MockPostAppealMessageUseCase is a mock of PostAppealMessageUseCase interface.
type MockPostAppealMessageUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPostAppealMessageUseCaseMockRecorder
	isgomock struct{}
}

// MockPostAppealMessageUseCaseMockRecorder is the mock recorder for MockPostAppealMessageUseCase.
type MockPostAppealMessageUseCaseMockRecorder struct {
	mock *MockPostAppealMessageUseCase
}

// NewMockPostAppealMessageUseCase creates a new mock instance.
func NewMockPostAppealMessageUseCase(ctrl *gomock.Controller) *MockPostAppealMessageUseCase {
	mock := &MockPostAppealMessageUseCase{ctrl: ctrl}
	mock.recorder = &MockPostAppealMessageUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostAppealMessageUseCase) EXPECT() *MockPostAppealMessageUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockPostAppealMessageUseCase) Execute(arg0 context.Context, arg1 dto.PostAppealMessageInput) (dto.PostAppealMessageOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.PostAppealMessageOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockPostAppealMessageUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockPostAppealMessageUseCase)(nil).Execute), arg0, arg1)
}

// MockGetAppealMessageUseCase is a mock of GetAppealMessageUseCase interface.
type MockGetAppealMessageUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetAppealMessageUseCaseMockRecorder
	isgomock struct{}
}

// MockGetAppealMessageUseCaseMockRecorder is the mock recorder for MockGetAppealMessageUseCase.
type MockGetAppealMessageUseCaseMockRecorder struct {
	mock *MockGetAppealMessageUseCase
}

// NewMockGetAppealMessageUseCase creates a new mock instance.
func NewMockGetAppealMessageUseCase(ctrl *gomock.Controller) *MockGetAppealMessageUseCase {
	mock := &MockGetAppealMessageUseCase{ctrl: ctrl}
	mock.recorder = &MockGetAppealMessageUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetAppealMessageUseCase) EXPECT() *MockGetAppealMessageUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetAppealMessageUseCase) Execute(arg0 context.Context, arg1 dto.GetAppealMessageInput) (dto.GetAppealMessageOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetAppealMessageOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetAppealMessageUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetAppealMessageUseCase)(nil).Execute), arg0, arg1)
}

// MockGetAppealAllUseCase is a mock of GetAppealAllUseCase interface.
type MockGetAppealAllUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetAppealAllUseCaseMockRecorder
	isgomock struct{}
}

// MockGetAppealAllUseCaseMockRecorder is the mock recorder for MockGetAppealAllUseCase.
type MockGetAppealAllUseCaseMockRecorder struct {
	mock *MockGetAppealAllUseCase
}

// NewMockGetAppealAllUseCase creates a new mock instance.
func NewMockGetAppealAllUseCase(ctrl *gomock.Controller) *MockGetAppealAllUseCase {
	mock := &MockGetAppealAllUseCase{ctrl: ctrl}
	mock.recorder = &MockGetAppealAllUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetAppealAllUseCase) EXPECT() *MockGetAppealAllUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetAppealAllUseCase) Execute(arg0 context.Context, arg1 dto.GetAppealAllInput) (dto.GetAppealAllOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetAppealAllOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetAppealAllUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetAppealAllUseCase)(nil).Execute), arg0, arg1)
}

// MockGetSearchUseCase is a mock of GetSearchUseCase interface.
type MockGetSearchUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetSearchUseCaseMockRecorder
	isgomock struct{}
}

// MockGetSearchUseCaseMockRecorder is the mock recorder for MockGetSearchUseCase.
type MockGetSearchUseCaseMockRecorder struct {
	mock *MockGetSearchUseCase
}

// NewMockGetSearchUseCase creates a new mock instance.
func NewMockGetSearchUseCase(ctrl *gomock.Controller) *MockGetSearchUseCase {
	mock := &MockGetSearchUseCase{ctrl: ctrl}
	mock.recorder = &MockGetSearchUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetSearchUseCase) EXPECT() *MockGetSearchUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetSearchUseCase) Execute(arg0 context.Context, arg1 dto.GetSearchInput) (dto.GetSearchOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetSearchOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetSearchUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetSearchUseCase)(nil).Execute), arg0, arg1)
}

// MockGetMediaLikeUseCase is a mock of GetMediaLikeUseCase interface.
type MockGetMediaLikeUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetMediaLikeUseCaseMockRecorder
	isgomock struct{}
}

// MockGetMediaLikeUseCaseMockRecorder is the mock recorder for MockGetMediaLikeUseCase.
type MockGetMediaLikeUseCaseMockRecorder struct {
	mock *MockGetMediaLikeUseCase
}

// NewMockGetMediaLikeUseCase creates a new mock instance.
func NewMockGetMediaLikeUseCase(ctrl *gomock.Controller) *MockGetMediaLikeUseCase {
	mock := &MockGetMediaLikeUseCase{ctrl: ctrl}
	mock.recorder = &MockGetMediaLikeUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetMediaLikeUseCase) EXPECT() *MockGetMediaLikeUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetMediaLikeUseCase) Execute(arg0 context.Context, arg1 dto.GetMediaLikeInput) (dto.GetMediaLikeOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetMediaLikeOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetMediaLikeUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetMediaLikeUseCase)(nil).Execute), arg0, arg1)
}

// MockPutMediaLikeUseCase is a mock of PutMediaLikeUseCase interface.
type MockPutMediaLikeUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPutMediaLikeUseCaseMockRecorder
	isgomock struct{}
}

// MockPutMediaLikeUseCaseMockRecorder is the mock recorder for MockPutMediaLikeUseCase.
type MockPutMediaLikeUseCaseMockRecorder struct {
	mock *MockPutMediaLikeUseCase
}

// NewMockPutMediaLikeUseCase creates a new mock instance.
func NewMockPutMediaLikeUseCase(ctrl *gomock.Controller) *MockPutMediaLikeUseCase {
	mock := &MockPutMediaLikeUseCase{ctrl: ctrl}
	mock.recorder = &MockPutMediaLikeUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPutMediaLikeUseCase) EXPECT() *MockPutMediaLikeUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockPutMediaLikeUseCase) Execute(arg0 context.Context, arg1 dto.PutMediaLikeInput) (dto.PutMediaLikeOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.PutMediaLikeOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockPutMediaLikeUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockPutMediaLikeUseCase)(nil).Execute), arg0, arg1)
}

// MockDeleteMediaLikeUseCase is a mock of DeleteMediaLikeUseCase interface.
type MockDeleteMediaLikeUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteMediaLikeUseCaseMockRecorder
	isgomock struct{}
}

// MockDeleteMediaLikeUseCaseMockRecorder is the mock recorder for MockDeleteMediaLikeUseCase.
type MockDeleteMediaLikeUseCaseMockRecorder struct {
	mock *MockDeleteMediaLikeUseCase
}

// NewMockDeleteMediaLikeUseCase creates a new mock instance.
func NewMockDeleteMediaLikeUseCase(ctrl *gomock.Controller) *MockDeleteMediaLikeUseCase {
	mock := &MockDeleteMediaLikeUseCase{ctrl: ctrl}
	mock.recorder = &MockDeleteMediaLikeUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteMediaLikeUseCase) EXPECT() *MockDeleteMediaLikeUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeleteMediaLikeUseCase) Execute(arg0 context.Context, arg1 dto.DeleteMediaLikeInput) (dto.DeleteMediaLikeOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.DeleteMediaLikeOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockDeleteMediaLikeUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteMediaLikeUseCase)(nil).Execute), arg0, arg1)
}

// MockGetMediaMyUseCase is a mock of GetMediaMyUseCase interface.
type MockGetMediaMyUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetMediaMyUseCaseMockRecorder
	isgomock struct{}
}

// MockGetMediaMyUseCaseMockRecorder is the mock recorder for MockGetMediaMyUseCase.
type MockGetMediaMyUseCaseMockRecorder struct {
	mock *MockGetMediaMyUseCase
}

// NewMockGetMediaMyUseCase creates a new mock instance.
func NewMockGetMediaMyUseCase(ctrl *gomock.Controller) *MockGetMediaMyUseCase {
	mock := &MockGetMediaMyUseCase{ctrl: ctrl}
	mock.recorder = &MockGetMediaMyUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetMediaMyUseCase) EXPECT() *MockGetMediaMyUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetMediaMyUseCase) Execute(arg0 context.Context, arg1 dto.GetMediaMyInput) (dto.GetMediaMyOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetMediaMyOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetMediaMyUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetMediaMyUseCase)(nil).Execute), arg0, arg1)
}

// MockGetGenreUseCase is a mock of GetGenreUseCase interface.
type MockGetGenreUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetGenreUseCaseMockRecorder
	isgomock struct{}
}

// MockGetGenreUseCaseMockRecorder is the mock recorder for MockGetGenreUseCase.
type MockGetGenreUseCaseMockRecorder struct {
	mock *MockGetGenreUseCase
}

// NewMockGetGenreUseCase creates a new mock instance.
func NewMockGetGenreUseCase(ctrl *gomock.Controller) *MockGetGenreUseCase {
	mock := &MockGetGenreUseCase{ctrl: ctrl}
	mock.recorder = &MockGetGenreUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetGenreUseCase) EXPECT() *MockGetGenreUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetGenreUseCase) Execute(arg0 context.Context, arg1 dto.GetGenreInput) (dto.GetGenreOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetGenreOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetGenreUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetGenreUseCase)(nil).Execute), arg0, arg1)
}

// MockGetGenreAllUseCase is a mock of GetGenreAllUseCase interface.
type MockGetGenreAllUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetGenreAllUseCaseMockRecorder
	isgomock struct{}
}

// MockGetGenreAllUseCaseMockRecorder is the mock recorder for MockGetGenreAllUseCase.
type MockGetGenreAllUseCaseMockRecorder struct {
	mock *MockGetGenreAllUseCase
}

// NewMockGetGenreAllUseCase creates a new mock instance.
func NewMockGetGenreAllUseCase(ctrl *gomock.Controller) *MockGetGenreAllUseCase {
	mock := &MockGetGenreAllUseCase{ctrl: ctrl}
	mock.recorder = &MockGetGenreAllUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetGenreAllUseCase) EXPECT() *MockGetGenreAllUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetGenreAllUseCase) Execute(arg0 context.Context, arg1 dto.GetGenreAllInput) (dto.GetGenreAllOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetGenreAllOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetGenreAllUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetGenreAllUseCase)(nil).Execute), arg0, arg1)
}
