// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
  "fmt"
  "os"

  "github.com/mailru/easyjson/gen"

  pkg "github.com/go-park-mail-ru/2025_2_Suzuki_plus_one/internal/dto"
)

func main() {
  g := gen.NewGenerator("delete_media_like_easyjson.go")
  g.SetPkg("dto", "github.com/go-park-mail-ru/2025_2_Suzuki_plus_one/internal/dto")
  g.Add(pkg.EasyJSON_exporter_DeleteMediaLikeInput(nil))
  g.Add(pkg.EasyJSON_exporter_DeleteMediaLikeOutput(nil))
  if err := g.Run(os.Stdout); err != nil {
    fmt.Fprintln(os.Stderr, err)
    os.Exit(1)
  }
}
