// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson63ddedacDecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(in *jlexer.Lexer, out *GetActorOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "image_urls":
			if in.IsNull() {
				in.Skip()
				out.ImageURLs = nil
			} else {
				in.Delim('[')
				if out.ImageURLs == nil {
					if !in.IsDelim(']') {
						out.ImageURLs = make([]string, 0, 4)
					} else {
						out.ImageURLs = []string{}
					}
				} else {
					out.ImageURLs = (out.ImageURLs)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.ImageURLs = append(out.ImageURLs, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = uint(in.Uint())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "birth_date":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.BirthDate).UnmarshalJSON(data))
				}
			}
		case "bio":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Bio = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson63ddedacEncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(out *jwriter.Writer, in GetActorOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"image_urls\":"
		out.RawString(prefix[1:])
		if in.ImageURLs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.ImageURLs {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.Uint(uint(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"birth_date\":"
		out.RawString(prefix)
		out.Raw((in.BirthDate).MarshalJSON())
	}
	{
		const prefix string = ",\"bio\":"
		out.RawString(prefix)
		out.String(string(in.Bio))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetActorOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson63ddedacEncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetActorOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson63ddedacEncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetActorOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson63ddedacDecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetActorOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson63ddedacDecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(l, v)
}
func easyjson63ddedacDecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(in *jlexer.Lexer, out *GetActorInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "actor_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ActorID = uint(in.Uint())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson63ddedacEncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(out *jwriter.Writer, in GetActorInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"actor_id\":"
		out.RawString(prefix[1:])
		out.Uint(uint(in.ActorID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetActorInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson63ddedacEncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetActorInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson63ddedacEncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetActorInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson63ddedacDecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetActorInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson63ddedacDecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(l, v)
}
