// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson58832f22DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(in *jlexer.Lexer, out *GetMediaEpisodesOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "episodes":
			if in.IsNull() {
				in.Skip()
				out.Episodes = nil
			} else {
				in.Delim('[')
				if out.Episodes == nil {
					if !in.IsDelim(']') {
						out.Episodes = make([]GetMediaEpisodeOutput, 0, 0)
					} else {
						out.Episodes = []GetMediaEpisodeOutput{}
					}
				} else {
					out.Episodes = (out.Episodes)[:0]
				}
				for !in.IsDelim(']') {
					var v1 GetMediaEpisodeOutput
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Episodes = append(out.Episodes, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson58832f22EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(out *jwriter.Writer, in GetMediaEpisodesOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"episodes\":"
		out.RawString(prefix[1:])
		if in.Episodes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Episodes {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetMediaEpisodesOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson58832f22EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetMediaEpisodesOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson58832f22EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetMediaEpisodesOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson58832f22DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetMediaEpisodesOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson58832f22DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(l, v)
}
func easyjson58832f22DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(in *jlexer.Lexer, out *GetMediaEpisodesInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "media_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MediaID = uint(in.Uint())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson58832f22EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(out *jwriter.Writer, in GetMediaEpisodesInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"media_id\":"
		out.RawString(prefix[1:])
		out.Uint(uint(in.MediaID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetMediaEpisodesInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson58832f22EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetMediaEpisodesInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson58832f22EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetMediaEpisodesInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson58832f22DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetMediaEpisodesInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson58832f22DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(l, v)
}
func easyjson58832f22DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto2(in *jlexer.Lexer, out *GetMediaEpisodeOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "media":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Media).UnmarshalEasyJSON(in)
			}
		case "episode_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EpisodeID = uint(in.Uint())
			}
		case "series_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SeriesID = uint(in.Uint())
			}
		case "season_number":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SeasonNumber = int(in.Int())
			}
		case "episode_number":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EpisodeNumber = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson58832f22EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto2(out *jwriter.Writer, in GetMediaEpisodeOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"media\":"
		out.RawString(prefix[1:])
		(in.Media).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"episode_id\":"
		out.RawString(prefix)
		out.Uint(uint(in.EpisodeID))
	}
	{
		const prefix string = ",\"series_id\":"
		out.RawString(prefix)
		out.Uint(uint(in.SeriesID))
	}
	{
		const prefix string = ",\"season_number\":"
		out.RawString(prefix)
		out.Int(int(in.SeasonNumber))
	}
	{
		const prefix string = ",\"episode_number\":"
		out.RawString(prefix)
		out.Int(int(in.EpisodeNumber))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetMediaEpisodeOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson58832f22EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetMediaEpisodeOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson58832f22EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetMediaEpisodeOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson58832f22DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetMediaEpisodeOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson58832f22DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto2(l, v)
}
