// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson344174faDecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(in *jlexer.Lexer, out *GetGenreAllOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "genres":
			if in.IsNull() {
				in.Skip()
				out.Genres = nil
			} else {
				in.Delim('[')
				if out.Genres == nil {
					if !in.IsDelim(']') {
						out.Genres = make([]GetGenreOutput, 0, 1)
					} else {
						out.Genres = []GetGenreOutput{}
					}
				} else {
					out.Genres = (out.Genres)[:0]
				}
				for !in.IsDelim(']') {
					var v1 GetGenreOutput
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Genres = append(out.Genres, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson344174faEncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(out *jwriter.Writer, in GetGenreAllOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"genres\":"
		out.RawString(prefix[1:])
		if in.Genres == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Genres {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetGenreAllOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson344174faEncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetGenreAllOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson344174faEncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetGenreAllOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson344174faDecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetGenreAllOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson344174faDecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(l, v)
}
func easyjson344174faDecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(in *jlexer.Lexer, out *GetGenreAllInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson344174faEncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(out *jwriter.Writer, in GetGenreAllInput) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetGenreAllInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson344174faEncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetGenreAllInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson344174faEncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetGenreAllInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson344174faDecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetGenreAllInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson344174faDecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(l, v)
}
