// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonAcf6ba22DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(in *jlexer.Lexer, out *GetAppealAllOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "appeals":
			if in.IsNull() {
				in.Skip()
				out.Appeals = nil
			} else {
				in.Delim('[')
				if out.Appeals == nil {
					if !in.IsDelim(']') {
						out.Appeals = make([]GetAppealOutput, 0, 0)
					} else {
						out.Appeals = []GetAppealOutput{}
					}
				} else {
					out.Appeals = (out.Appeals)[:0]
				}
				for !in.IsDelim(']') {
					var v1 GetAppealOutput
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Appeals = append(out.Appeals, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAcf6ba22EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(out *jwriter.Writer, in GetAppealAllOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"appeals\":"
		out.RawString(prefix[1:])
		if in.Appeals == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Appeals {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetAppealAllOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAcf6ba22EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetAppealAllOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAcf6ba22EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetAppealAllOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAcf6ba22DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetAppealAllOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAcf6ba22DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(l, v)
}
func easyjsonAcf6ba22DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(in *jlexer.Lexer, out *GetAppealAllInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Tag":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Tag = string(in.String())
			}
		case "Status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "Limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = uint(in.Uint())
			}
		case "Offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = uint(in.Uint())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAcf6ba22EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(out *jwriter.Writer, in GetAppealAllInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Tag\":"
		out.RawString(prefix[1:])
		out.String(string(in.Tag))
	}
	{
		const prefix string = ",\"Status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"Limit\":"
		out.RawString(prefix)
		out.Uint(uint(in.Limit))
	}
	{
		const prefix string = ",\"Offset\":"
		out.RawString(prefix)
		out.Uint(uint(in.Offset))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetAppealAllInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAcf6ba22EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetAppealAllInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAcf6ba22EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetAppealAllInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAcf6ba22DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetAppealAllInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAcf6ba22DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(l, v)
}
