// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6fcbc553DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(in *jlexer.Lexer, out *MediaRating) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "likes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Likes = uint(in.Uint())
			}
		case "dislikes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Dislikes = uint(in.Uint())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6fcbc553EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(out *jwriter.Writer, in MediaRating) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"likes\":"
		out.RawString(prefix[1:])
		out.Uint(uint(in.Likes))
	}
	{
		const prefix string = ",\"dislikes\":"
		out.RawString(prefix)
		out.Uint(uint(in.Dislikes))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MediaRating) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6fcbc553EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MediaRating) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6fcbc553EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MediaRating) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6fcbc553DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MediaRating) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6fcbc553DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(l, v)
}
func easyjson6fcbc553DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(in *jlexer.Lexer, out *GetMediaOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "genres":
			if in.IsNull() {
				in.Skip()
				out.Genres = nil
			} else {
				in.Delim('[')
				if out.Genres == nil {
					if !in.IsDelim(']') {
						out.Genres = make([]GetGenreOutput, 0, 1)
					} else {
						out.Genres = []GetGenreOutput{}
					}
				} else {
					out.Genres = (out.Genres)[:0]
				}
				for !in.IsDelim(']') {
					var v1 GetGenreOutput
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Genres = append(out.Genres, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "posters":
			if in.IsNull() {
				in.Skip()
				out.Posters = nil
			} else {
				in.Delim('[')
				if out.Posters == nil {
					if !in.IsDelim(']') {
						out.Posters = make([]string, 0, 4)
					} else {
						out.Posters = []string{}
					}
				} else {
					out.Posters = (out.Posters)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = string(in.String())
					}
					out.Posters = append(out.Posters, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "trailers":
			if in.IsNull() {
				in.Skip()
				out.Trailers = nil
			} else {
				in.Delim('[')
				if out.Trailers == nil {
					if !in.IsDelim(']') {
						out.Trailers = make([]string, 0, 4)
					} else {
						out.Trailers = []string{}
					}
				} else {
					out.Trailers = (out.Trailers)[:0]
				}
				for !in.IsDelim(']') {
					var v3 string
					if in.IsNull() {
						in.Skip()
					} else {
						v3 = string(in.String())
					}
					out.Trailers = append(out.Trailers, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "user_rating":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.UserRating).UnmarshalEasyJSON(in)
			}
		case "media_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MediaID = uint(in.Uint())
			}
		case "media_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MediaType = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "release_date":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.ReleaseDate).UnmarshalJSON(data))
				}
			}
		case "rating":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rating = float64(in.Float64())
			}
		case "duration_minutes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Duration = int(in.Int())
			}
		case "age_rating":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AgeRating = int(in.Int())
			}
		case "country":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Country = string(in.String())
			}
		case "plot_summary":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PlotSummary = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6fcbc553EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(out *jwriter.Writer, in GetMediaOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"genres\":"
		out.RawString(prefix[1:])
		if in.Genres == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v4, v5 := range in.Genres {
				if v4 > 0 {
					out.RawByte(',')
				}
				(v5).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"posters\":"
		out.RawString(prefix)
		if in.Posters == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v6, v7 := range in.Posters {
				if v6 > 0 {
					out.RawByte(',')
				}
				out.String(string(v7))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"trailers\":"
		out.RawString(prefix)
		if in.Trailers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Trailers {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.String(string(v9))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"user_rating\":"
		out.RawString(prefix)
		(in.UserRating).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"media_id\":"
		out.RawString(prefix)
		out.Uint(uint(in.MediaID))
	}
	{
		const prefix string = ",\"media_type\":"
		out.RawString(prefix)
		out.String(string(in.MediaType))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	if true {
		const prefix string = ",\"release_date\":"
		out.RawString(prefix)
		out.Raw((in.ReleaseDate).MarshalJSON())
	}
	if in.Rating != 0 {
		const prefix string = ",\"rating\":"
		out.RawString(prefix)
		out.Float64(float64(in.Rating))
	}
	if in.Duration != 0 {
		const prefix string = ",\"duration_minutes\":"
		out.RawString(prefix)
		out.Int(int(in.Duration))
	}
	if in.AgeRating != 0 {
		const prefix string = ",\"age_rating\":"
		out.RawString(prefix)
		out.Int(int(in.AgeRating))
	}
	if in.Country != "" {
		const prefix string = ",\"country\":"
		out.RawString(prefix)
		out.String(string(in.Country))
	}
	if in.PlotSummary != "" {
		const prefix string = ",\"plot_summary\":"
		out.RawString(prefix)
		out.String(string(in.PlotSummary))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetMediaOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6fcbc553EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetMediaOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6fcbc553EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetMediaOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6fcbc553DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetMediaOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6fcbc553DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(l, v)
}
func easyjson6fcbc553DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto2(in *jlexer.Lexer, out *GetMediaInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "media_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MediaID = uint(in.Uint())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6fcbc553EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto2(out *jwriter.Writer, in GetMediaInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"media_id\":"
		out.RawString(prefix[1:])
		out.Uint(uint(in.MediaID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetMediaInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6fcbc553EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetMediaInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6fcbc553EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetMediaInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6fcbc553DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetMediaInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6fcbc553DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto2(l, v)
}
