// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson86d0c9e5DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(in *jlexer.Lexer, out *PostUserMeUpdateAvatarOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.URL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson86d0c9e5EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(out *jwriter.Writer, in PostUserMeUpdateAvatarOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix[1:])
		out.String(string(in.URL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PostUserMeUpdateAvatarOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson86d0c9e5EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PostUserMeUpdateAvatarOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson86d0c9e5EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PostUserMeUpdateAvatarOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson86d0c9e5DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PostUserMeUpdateAvatarOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson86d0c9e5DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(l, v)
}
func easyjson86d0c9e5DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(in *jlexer.Lexer, out *PostUserMeUpdateAvatarInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "access_token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccessToken = string(in.String())
			}
		case "avatar":
			if in.IsNull() {
				in.Skip()
				out.Bytes = nil
			} else {
				out.Bytes = in.Bytes()
			}
		case "mime_format":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MimeFormat = string(in.String())
			}
		case "file_size_mb":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FileSizeMB = float32(in.Float32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson86d0c9e5EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(out *jwriter.Writer, in PostUserMeUpdateAvatarInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"access_token\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccessToken))
	}
	{
		const prefix string = ",\"avatar\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Bytes)
	}
	{
		const prefix string = ",\"mime_format\":"
		out.RawString(prefix)
		out.String(string(in.MimeFormat))
	}
	{
		const prefix string = ",\"file_size_mb\":"
		out.RawString(prefix)
		out.Float32(float32(in.FileSizeMB))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PostUserMeUpdateAvatarInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson86d0c9e5EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PostUserMeUpdateAvatarInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson86d0c9e5EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PostUserMeUpdateAvatarInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson86d0c9e5DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PostUserMeUpdateAvatarInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson86d0c9e5DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(l, v)
}
