// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson630ec409DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(in *jlexer.Lexer, out *PostUserMeUpdatePasswordOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson630ec409EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(out *jwriter.Writer, in PostUserMeUpdatePasswordOutput) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PostUserMeUpdatePasswordOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson630ec409EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PostUserMeUpdatePasswordOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson630ec409EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PostUserMeUpdatePasswordOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson630ec409DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PostUserMeUpdatePasswordOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson630ec409DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(l, v)
}
func easyjson630ec409DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(in *jlexer.Lexer, out *PostUserMeUpdatePasswordInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "access_token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccessToken = string(in.String())
			}
		case "current_password":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CurrentPassword = string(in.String())
			}
		case "new_password":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NewPassword = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson630ec409EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(out *jwriter.Writer, in PostUserMeUpdatePasswordInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"access_token\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccessToken))
	}
	{
		const prefix string = ",\"current_password\":"
		out.RawString(prefix)
		out.String(string(in.CurrentPassword))
	}
	{
		const prefix string = ",\"new_password\":"
		out.RawString(prefix)
		out.String(string(in.NewPassword))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PostUserMeUpdatePasswordInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson630ec409EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PostUserMeUpdatePasswordInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson630ec409EncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PostUserMeUpdatePasswordInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson630ec409DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PostUserMeUpdatePasswordInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson630ec409DecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(l, v)
}
