// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson56b052cDecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(in *jlexer.Lexer, out *PostAuthSignInOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "access_token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccessToken = string(in.String())
			}
		case "refresh_token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RefreshToken = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56b052cEncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(out *jwriter.Writer, in PostAuthSignInOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"access_token\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccessToken))
	}
	{
		const prefix string = ",\"refresh_token\":"
		out.RawString(prefix)
		out.String(string(in.RefreshToken))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PostAuthSignInOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56b052cEncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PostAuthSignInOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56b052cEncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PostAuthSignInOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56b052cDecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PostAuthSignInOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56b052cDecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto(l, v)
}
func easyjson56b052cDecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(in *jlexer.Lexer, out *PostAuthSignInInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		case "password":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Password = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56b052cEncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(out *jwriter.Writer, in PostAuthSignInInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix[1:])
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PostAuthSignInInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56b052cEncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PostAuthSignInInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56b052cEncodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PostAuthSignInInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56b052cDecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PostAuthSignInInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56b052cDecodeGithubComGoParkMailRu20252SuzukiPlusOneInternalDto1(l, v)
}
