// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./mocks/contract_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/go-park-mail-ru/2025_2_Suzuki_plus_one/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockMediaRepository is a mock of MediaRepository interface.
type MockMediaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMediaRepositoryMockRecorder
	isgomock struct{}
}

// MockMediaRepositoryMockRecorder is the mock recorder for MockMediaRepository.
type MockMediaRepositoryMockRecorder struct {
	mock *MockMediaRepository
}

// NewMockMediaRepository creates a new mock instance.
func NewMockMediaRepository(ctrl *gomock.Controller) *MockMediaRepository {
	mock := &MockMediaRepository{ctrl: ctrl}
	mock.recorder = &MockMediaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaRepository) EXPECT() *MockMediaRepositoryMockRecorder {
	return m.recorder
}

// GetMediaByID mocks base method.
func (m *MockMediaRepository) GetMediaByID(ctx context.Context, media_id uint) (*entity.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaByID", ctx, media_id)
	ret0, _ := ret[0].(*entity.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaByID indicates an expected call of GetMediaByID.
func (mr *MockMediaRepositoryMockRecorder) GetMediaByID(ctx, media_id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaByID", reflect.TypeOf((*MockMediaRepository)(nil).GetMediaByID), ctx, media_id)
}

// GetMediaCount mocks base method.
func (m *MockMediaRepository) GetMediaCount(ctx context.Context, media_type string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaCount", ctx, media_type)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaCount indicates an expected call of GetMediaCount.
func (mr *MockMediaRepositoryMockRecorder) GetMediaCount(ctx, media_type any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaCount", reflect.TypeOf((*MockMediaRepository)(nil).GetMediaCount), ctx, media_type)
}

// GetMediaGenres mocks base method.
func (m *MockMediaRepository) GetMediaGenres(ctx context.Context, media_id uint) ([]entity.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaGenres", ctx, media_id)
	ret0, _ := ret[0].([]entity.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaGenres indicates an expected call of GetMediaGenres.
func (mr *MockMediaRepositoryMockRecorder) GetMediaGenres(ctx, media_id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaGenres", reflect.TypeOf((*MockMediaRepository)(nil).GetMediaGenres), ctx, media_id)
}

// GetMediaIDsByLikeStatus mocks base method.
func (m *MockMediaRepository) GetMediaIDsByLikeStatus(ctx context.Context, userID uint, isDislike bool, limit, offset uint) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaIDsByLikeStatus", ctx, userID, isDislike, limit, offset)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaIDsByLikeStatus indicates an expected call of GetMediaIDsByLikeStatus.
func (mr *MockMediaRepositoryMockRecorder) GetMediaIDsByLikeStatus(ctx, userID, isDislike, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaIDsByLikeStatus", reflect.TypeOf((*MockMediaRepository)(nil).GetMediaIDsByLikeStatus), ctx, userID, isDislike, limit, offset)
}

// GetMediaPostersKeys mocks base method.
func (m *MockMediaRepository) GetMediaPostersKeys(ctx context.Context, media_id uint) ([]entity.S3Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaPostersKeys", ctx, media_id)
	ret0, _ := ret[0].([]entity.S3Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaPostersKeys indicates an expected call of GetMediaPostersKeys.
func (mr *MockMediaRepositoryMockRecorder) GetMediaPostersKeys(ctx, media_id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaPostersKeys", reflect.TypeOf((*MockMediaRepository)(nil).GetMediaPostersKeys), ctx, media_id)
}

// GetMediaSortedByName mocks base method.
func (m *MockMediaRepository) GetMediaSortedByName(ctx context.Context, limit, offset uint, media_type string) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaSortedByName", ctx, limit, offset, media_type)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaSortedByName indicates an expected call of GetMediaSortedByName.
func (mr *MockMediaRepositoryMockRecorder) GetMediaSortedByName(ctx, limit, offset, media_type any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaSortedByName", reflect.TypeOf((*MockMediaRepository)(nil).GetMediaSortedByName), ctx, limit, offset, media_type)
}

// GetMediaTrailersKeys mocks base method.
func (m *MockMediaRepository) GetMediaTrailersKeys(ctx context.Context, media_id uint) ([]entity.S3Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaTrailersKeys", ctx, media_id)
	ret0, _ := ret[0].([]entity.S3Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaTrailersKeys indicates an expected call of GetMediaTrailersKeys.
func (mr *MockMediaRepositoryMockRecorder) GetMediaTrailersKeys(ctx, media_id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaTrailersKeys", reflect.TypeOf((*MockMediaRepository)(nil).GetMediaTrailersKeys), ctx, media_id)
}

// GetMediaWatchKey mocks base method.
func (m *MockMediaRepository) GetMediaWatchKey(ctx context.Context, media_id uint) (*entity.S3Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaWatchKey", ctx, media_id)
	ret0, _ := ret[0].(*entity.S3Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaWatchKey indicates an expected call of GetMediaWatchKey.
func (mr *MockMediaRepositoryMockRecorder) GetMediaWatchKey(ctx, media_id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaWatchKey", reflect.TypeOf((*MockMediaRepository)(nil).GetMediaWatchKey), ctx, media_id)
}

// GetMediasByGenreID mocks base method.
func (m *MockMediaRepository) GetMediasByGenreID(ctx context.Context, limit, offset, genreID uint) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediasByGenreID", ctx, limit, offset, genreID)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediasByGenreID indicates an expected call of GetMediasByGenreID.
func (mr *MockMediaRepositoryMockRecorder) GetMediasByGenreID(ctx, limit, offset, genreID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediasByGenreID", reflect.TypeOf((*MockMediaRepository)(nil).GetMediasByGenreID), ctx, limit, offset, genreID)
}

// MockGenreRepository is a mock of GenreRepository interface.
type MockGenreRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGenreRepositoryMockRecorder
	isgomock struct{}
}

// MockGenreRepositoryMockRecorder is the mock recorder for MockGenreRepository.
type MockGenreRepositoryMockRecorder struct {
	mock *MockGenreRepository
}

// NewMockGenreRepository creates a new mock instance.
func NewMockGenreRepository(ctrl *gomock.Controller) *MockGenreRepository {
	mock := &MockGenreRepository{ctrl: ctrl}
	mock.recorder = &MockGenreRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenreRepository) EXPECT() *MockGenreRepositoryMockRecorder {
	return m.recorder
}

// GetAllGenreIDs mocks base method.
func (m *MockGenreRepository) GetAllGenreIDs(ctx context.Context) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllGenreIDs", ctx)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllGenreIDs indicates an expected call of GetAllGenreIDs.
func (mr *MockGenreRepositoryMockRecorder) GetAllGenreIDs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllGenreIDs", reflect.TypeOf((*MockGenreRepository)(nil).GetAllGenreIDs), ctx)
}

// GetGenreByID mocks base method.
func (m *MockGenreRepository) GetGenreByID(ctx context.Context, genreID uint) (*entity.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenreByID", ctx, genreID)
	ret0, _ := ret[0].(*entity.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenreByID indicates an expected call of GetGenreByID.
func (mr *MockGenreRepositoryMockRecorder) GetGenreByID(ctx, genreID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenreByID", reflect.TypeOf((*MockGenreRepository)(nil).GetGenreByID), ctx, genreID)
}

// MockLikeRepository is a mock of LikeRepository interface.
type MockLikeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLikeRepositoryMockRecorder
	isgomock struct{}
}

// MockLikeRepositoryMockRecorder is the mock recorder for MockLikeRepository.
type MockLikeRepositoryMockRecorder struct {
	mock *MockLikeRepository
}

// NewMockLikeRepository creates a new mock instance.
func NewMockLikeRepository(ctrl *gomock.Controller) *MockLikeRepository {
	mock := &MockLikeRepository{ctrl: ctrl}
	mock.recorder = &MockLikeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikeRepository) EXPECT() *MockLikeRepositoryMockRecorder {
	return m.recorder
}

// DeleteLike mocks base method.
func (m *MockLikeRepository) DeleteLike(ctx context.Context, userID, mediaID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLike", ctx, userID, mediaID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLike indicates an expected call of DeleteLike.
func (mr *MockLikeRepositoryMockRecorder) DeleteLike(ctx, userID, mediaID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLike", reflect.TypeOf((*MockLikeRepository)(nil).DeleteLike), ctx, userID, mediaID)
}

// GetLike mocks base method.
func (m *MockLikeRepository) GetLike(ctx context.Context, userID, mediaID uint) (bool, entity.Like, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLike", ctx, userID, mediaID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(entity.Like)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLike indicates an expected call of GetLike.
func (mr *MockLikeRepositoryMockRecorder) GetLike(ctx, userID, mediaID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLike", reflect.TypeOf((*MockLikeRepository)(nil).GetLike), ctx, userID, mediaID)
}

// ToggleLike mocks base method.
func (m *MockLikeRepository) ToggleLike(ctx context.Context, userID, mediaID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleLike", ctx, userID, mediaID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleLike indicates an expected call of ToggleLike.
func (mr *MockLikeRepositoryMockRecorder) ToggleLike(ctx, userID, mediaID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleLike", reflect.TypeOf((*MockLikeRepository)(nil).ToggleLike), ctx, userID, mediaID)
}

// MockActorRepository is a mock of ActorRepository interface.
type MockActorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockActorRepositoryMockRecorder
	isgomock struct{}
}

// MockActorRepositoryMockRecorder is the mock recorder for MockActorRepository.
type MockActorRepositoryMockRecorder struct {
	mock *MockActorRepository
}

// NewMockActorRepository creates a new mock instance.
func NewMockActorRepository(ctrl *gomock.Controller) *MockActorRepository {
	mock := &MockActorRepository{ctrl: ctrl}
	mock.recorder = &MockActorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActorRepository) EXPECT() *MockActorRepositoryMockRecorder {
	return m.recorder
}

// GetActorByID mocks base method.
func (m *MockActorRepository) GetActorByID(ctx context.Context, actorID uint) (*entity.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorByID", ctx, actorID)
	ret0, _ := ret[0].(*entity.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActorByID indicates an expected call of GetActorByID.
func (mr *MockActorRepositoryMockRecorder) GetActorByID(ctx, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorByID", reflect.TypeOf((*MockActorRepository)(nil).GetActorByID), ctx, actorID)
}

// GetActorImageS3 mocks base method.
func (m *MockActorRepository) GetActorImageS3(ctx context.Context, actorID uint) ([]entity.S3Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorImageS3", ctx, actorID)
	ret0, _ := ret[0].([]entity.S3Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActorImageS3 indicates an expected call of GetActorImageS3.
func (mr *MockActorRepositoryMockRecorder) GetActorImageS3(ctx, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorImageS3", reflect.TypeOf((*MockActorRepository)(nil).GetActorImageS3), ctx, actorID)
}

// GetActorsByMediaID mocks base method.
func (m *MockActorRepository) GetActorsByMediaID(ctx context.Context, media_id uint) ([]entity.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorsByMediaID", ctx, media_id)
	ret0, _ := ret[0].([]entity.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActorsByMediaID indicates an expected call of GetActorsByMediaID.
func (mr *MockActorRepositoryMockRecorder) GetActorsByMediaID(ctx, media_id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorsByMediaID", reflect.TypeOf((*MockActorRepository)(nil).GetActorsByMediaID), ctx, media_id)
}

// GetMediasByActorID mocks base method.
func (m *MockActorRepository) GetMediasByActorID(ctx context.Context, actorID uint) ([]entity.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediasByActorID", ctx, actorID)
	ret0, _ := ret[0].([]entity.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediasByActorID indicates an expected call of GetMediasByActorID.
func (mr *MockActorRepositoryMockRecorder) GetMediasByActorID(ctx, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediasByActorID", reflect.TypeOf((*MockActorRepository)(nil).GetMediasByActorID), ctx, actorID)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(ctx context.Context, email, username, passwordHash string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, email, username, passwordHash)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(ctx, email, username, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), ctx, email, username, passwordHash)
}

// GetUserAvatarKey mocks base method.
func (m *MockUserRepository) GetUserAvatarKey(ctx context.Context, userID uint) (*entity.S3Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAvatarKey", ctx, userID)
	ret0, _ := ret[0].(*entity.S3Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAvatarKey indicates an expected call of GetUserAvatarKey.
func (mr *MockUserRepositoryMockRecorder) GetUserAvatarKey(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAvatarKey", reflect.TypeOf((*MockUserRepository)(nil).GetUserAvatarKey), ctx, userID)
}

// GetUserByEmail mocks base method.
func (m *MockUserRepository) GetUserByEmail(ctx context.Context, email string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserRepositoryMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockUserRepository) GetUserByID(ctx context.Context, userID uint) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositoryMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepository)(nil).GetUserByID), ctx, userID)
}

// UpdateUser mocks base method.
func (m *MockUserRepository) UpdateUser(ctx context.Context, userID uint, username, email string, dateOfBirth time.Time, phoneNumber string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, userID, username, email, dateOfBirth, phoneNumber)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserRepositoryMockRecorder) UpdateUser(ctx, userID, username, email, dateOfBirth, phoneNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserRepository)(nil).UpdateUser), ctx, userID, username, email, dateOfBirth, phoneNumber)
}

// UpdateUserAvatarKey mocks base method.
func (m *MockUserRepository) UpdateUserAvatarKey(ctx context.Context, userID, assetImageID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserAvatarKey", ctx, userID, assetImageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserAvatarKey indicates an expected call of UpdateUserAvatarKey.
func (mr *MockUserRepositoryMockRecorder) UpdateUserAvatarKey(ctx, userID, assetImageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserAvatarKey", reflect.TypeOf((*MockUserRepository)(nil).UpdateUserAvatarKey), ctx, userID, assetImageID)
}

// UpdateUserPassword mocks base method.
func (m *MockUserRepository) UpdateUserPassword(ctx context.Context, userID uint, newHashedPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPassword", ctx, userID, newHashedPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPassword indicates an expected call of UpdateUserPassword.
func (mr *MockUserRepositoryMockRecorder) UpdateUserPassword(ctx, userID, newHashedPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPassword", reflect.TypeOf((*MockUserRepository)(nil).UpdateUserPassword), ctx, userID, newHashedPassword)
}

// MockAppealRepository is a mock of AppealRepository interface.
type MockAppealRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAppealRepositoryMockRecorder
	isgomock struct{}
}

// MockAppealRepositoryMockRecorder is the mock recorder for MockAppealRepository.
type MockAppealRepositoryMockRecorder struct {
	mock *MockAppealRepository
}

// NewMockAppealRepository creates a new mock instance.
func NewMockAppealRepository(ctrl *gomock.Controller) *MockAppealRepository {
	mock := &MockAppealRepository{ctrl: ctrl}
	mock.recorder = &MockAppealRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppealRepository) EXPECT() *MockAppealRepositoryMockRecorder {
	return m.recorder
}

// CreateAppeal mocks base method.
func (m *MockAppealRepository) CreateAppeal(ctx context.Context, userID uint, tag, name string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppeal", ctx, userID, tag, name)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAppeal indicates an expected call of CreateAppeal.
func (mr *MockAppealRepositoryMockRecorder) CreateAppeal(ctx, userID, tag, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppeal", reflect.TypeOf((*MockAppealRepository)(nil).CreateAppeal), ctx, userID, tag, name)
}

// CreateAppealMessage mocks base method.
func (m *MockAppealRepository) CreateAppealMessage(ctx context.Context, appealID uint, isResponse bool, message string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppealMessage", ctx, appealID, isResponse, message)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAppealMessage indicates an expected call of CreateAppealMessage.
func (mr *MockAppealRepositoryMockRecorder) CreateAppealMessage(ctx, appealID, isResponse, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppealMessage", reflect.TypeOf((*MockAppealRepository)(nil).CreateAppealMessage), ctx, appealID, isResponse, message)
}

// GetAppealByID mocks base method.
func (m *MockAppealRepository) GetAppealByID(ctx context.Context, appealID uint) (*entity.Appeal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppealByID", ctx, appealID)
	ret0, _ := ret[0].(*entity.Appeal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppealByID indicates an expected call of GetAppealByID.
func (mr *MockAppealRepositoryMockRecorder) GetAppealByID(ctx, appealID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppealByID", reflect.TypeOf((*MockAppealRepository)(nil).GetAppealByID), ctx, appealID)
}

// GetAppealIDsAll mocks base method.
func (m *MockAppealRepository) GetAppealIDsAll(ctx context.Context, tag, status *string, limit, offset uint) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppealIDsAll", ctx, tag, status, limit, offset)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppealIDsAll indicates an expected call of GetAppealIDsAll.
func (mr *MockAppealRepositoryMockRecorder) GetAppealIDsAll(ctx, tag, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppealIDsAll", reflect.TypeOf((*MockAppealRepository)(nil).GetAppealIDsAll), ctx, tag, status, limit, offset)
}

// GetAppealIDsByUserID mocks base method.
func (m *MockAppealRepository) GetAppealIDsByUserID(ctx context.Context, userID uint) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppealIDsByUserID", ctx, userID)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppealIDsByUserID indicates an expected call of GetAppealIDsByUserID.
func (mr *MockAppealRepositoryMockRecorder) GetAppealIDsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppealIDsByUserID", reflect.TypeOf((*MockAppealRepository)(nil).GetAppealIDsByUserID), ctx, userID)
}

// GetAppealMessagesByID mocks base method.
func (m *MockAppealRepository) GetAppealMessagesByID(ctx context.Context, appealID uint) ([]entity.AppealMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppealMessagesByID", ctx, appealID)
	ret0, _ := ret[0].([]entity.AppealMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppealMessagesByID indicates an expected call of GetAppealMessagesByID.
func (mr *MockAppealRepositoryMockRecorder) GetAppealMessagesByID(ctx, appealID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppealMessagesByID", reflect.TypeOf((*MockAppealRepository)(nil).GetAppealMessagesByID), ctx, appealID)
}

// UpdateAppealStatus mocks base method.
func (m *MockAppealRepository) UpdateAppealStatus(ctx context.Context, appealID uint, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAppealStatus", ctx, appealID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAppealStatus indicates an expected call of UpdateAppealStatus.
func (mr *MockAppealRepositoryMockRecorder) UpdateAppealStatus(ctx, appealID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppealStatus", reflect.TypeOf((*MockAppealRepository)(nil).UpdateAppealStatus), ctx, appealID, status)
}

// MockAssetRepository is a mock of AssetRepository interface.
type MockAssetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAssetRepositoryMockRecorder
	isgomock struct{}
}

// MockAssetRepositoryMockRecorder is the mock recorder for MockAssetRepository.
type MockAssetRepositoryMockRecorder struct {
	mock *MockAssetRepository
}

// NewMockAssetRepository creates a new mock instance.
func NewMockAssetRepository(ctrl *gomock.Controller) *MockAssetRepository {
	mock := &MockAssetRepository{ctrl: ctrl}
	mock.recorder = &MockAssetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssetRepository) EXPECT() *MockAssetRepositoryMockRecorder {
	return m.recorder
}

// CreateAsset mocks base method.
func (m *MockAssetRepository) CreateAsset(ctx context.Context, asset entity.Asset) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAsset", ctx, asset)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAsset indicates an expected call of CreateAsset.
func (mr *MockAssetRepositoryMockRecorder) CreateAsset(ctx, asset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAsset", reflect.TypeOf((*MockAssetRepository)(nil).CreateAsset), ctx, asset)
}

// CreateAssetImage mocks base method.
func (m *MockAssetRepository) CreateAssetImage(ctx context.Context, assetImage entity.AssetImage) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAssetImage", ctx, assetImage)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAssetImage indicates an expected call of CreateAssetImage.
func (mr *MockAssetRepositoryMockRecorder) CreateAssetImage(ctx, assetImage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAssetImage", reflect.TypeOf((*MockAssetRepository)(nil).CreateAssetImage), ctx, assetImage)
}

// GetAssetByID mocks base method.
func (m *MockAssetRepository) GetAssetByID(ctx context.Context, assetID uint) (*entity.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssetByID", ctx, assetID)
	ret0, _ := ret[0].(*entity.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssetByID indicates an expected call of GetAssetByID.
func (mr *MockAssetRepositoryMockRecorder) GetAssetByID(ctx, assetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssetByID", reflect.TypeOf((*MockAssetRepository)(nil).GetAssetByID), ctx, assetID)
}

// GetAssetImageByID mocks base method.
func (m *MockAssetRepository) GetAssetImageByID(ctx context.Context, assetImageID uint) (*entity.AssetImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssetImageByID", ctx, assetImageID)
	ret0, _ := ret[0].(*entity.AssetImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssetImageByID indicates an expected call of GetAssetImageByID.
func (mr *MockAssetRepositoryMockRecorder) GetAssetImageByID(ctx, assetImageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssetImageByID", reflect.TypeOf((*MockAssetRepository)(nil).GetAssetImageByID), ctx, assetImageID)
}

// MockObjectRepository is a mock of ObjectRepository interface.
type MockObjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockObjectRepositoryMockRecorder
	isgomock struct{}
}

// MockObjectRepositoryMockRecorder is the mock recorder for MockObjectRepository.
type MockObjectRepositoryMockRecorder struct {
	mock *MockObjectRepository
}

// NewMockObjectRepository creates a new mock instance.
func NewMockObjectRepository(ctrl *gomock.Controller) *MockObjectRepository {
	mock := &MockObjectRepository{ctrl: ctrl}
	mock.recorder = &MockObjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectRepository) EXPECT() *MockObjectRepositoryMockRecorder {
	return m.recorder
}

// DeleteObject mocks base method.
func (m *MockObjectRepository) DeleteObject(ctx context.Context, bucketName, objectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, bucketName, objectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockObjectRepositoryMockRecorder) DeleteObject(ctx, bucketName, objectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockObjectRepository)(nil).DeleteObject), ctx, bucketName, objectName)
}

// GeneratePresignedURL mocks base method.
func (m *MockObjectRepository) GeneratePresignedURL(ctx context.Context, bucketName, objectName string, expiration time.Duration) (*entity.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePresignedURL", ctx, bucketName, objectName, expiration)
	ret0, _ := ret[0].(*entity.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePresignedURL indicates an expected call of GeneratePresignedURL.
func (mr *MockObjectRepositoryMockRecorder) GeneratePresignedURL(ctx, bucketName, objectName, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePresignedURL", reflect.TypeOf((*MockObjectRepository)(nil).GeneratePresignedURL), ctx, bucketName, objectName, expiration)
}

// GeneratePublicURL mocks base method.
func (m *MockObjectRepository) GeneratePublicURL(ctx context.Context, bucketName, objectName string) (*entity.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePublicURL", ctx, bucketName, objectName)
	ret0, _ := ret[0].(*entity.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePublicURL indicates an expected call of GeneratePublicURL.
func (mr *MockObjectRepositoryMockRecorder) GeneratePublicURL(ctx, bucketName, objectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePublicURL", reflect.TypeOf((*MockObjectRepository)(nil).GeneratePublicURL), ctx, bucketName, objectName)
}

// UploadObject mocks base method.
func (m *MockObjectRepository) UploadObject(ctx context.Context, bucketName, objectName, mimeType string, data []byte) (*entity.S3Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadObject", ctx, bucketName, objectName, mimeType, data)
	ret0, _ := ret[0].(*entity.S3Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadObject indicates an expected call of UploadObject.
func (mr *MockObjectRepositoryMockRecorder) UploadObject(ctx, bucketName, objectName, mimeType, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadObject", reflect.TypeOf((*MockObjectRepository)(nil).UploadObject), ctx, bucketName, objectName, mimeType, data)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// AddSession mocks base method.
func (m *MockSessionRepository) AddSession(ctx context.Context, userID uint, accessToken string, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSession", ctx, userID, accessToken, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSession indicates an expected call of AddSession.
func (mr *MockSessionRepositoryMockRecorder) AddSession(ctx, userID, accessToken, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSession", reflect.TypeOf((*MockSessionRepository)(nil).AddSession), ctx, userID, accessToken, expiration)
}

// DeleteSession mocks base method.
func (m *MockSessionRepository) DeleteSession(ctx context.Context, userID uint, accessToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, userID, accessToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockSessionRepositoryMockRecorder) DeleteSession(ctx, userID, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockSessionRepository)(nil).DeleteSession), ctx, userID, accessToken)
}

// GetUserIDByAccessToken mocks base method.
func (m *MockSessionRepository) GetUserIDByAccessToken(ctx context.Context, accessToken string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDByAccessToken", ctx, accessToken)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDByAccessToken indicates an expected call of GetUserIDByAccessToken.
func (mr *MockSessionRepositoryMockRecorder) GetUserIDByAccessToken(ctx, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDByAccessToken", reflect.TypeOf((*MockSessionRepository)(nil).GetUserIDByAccessToken), ctx, accessToken)
}

// MockServiceAuthRepository is a mock of ServiceAuthRepository interface.
type MockServiceAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockServiceAuthRepositoryMockRecorder
	isgomock struct{}
}

// MockServiceAuthRepositoryMockRecorder is the mock recorder for MockServiceAuthRepository.
type MockServiceAuthRepositoryMockRecorder struct {
	mock *MockServiceAuthRepository
}

// NewMockServiceAuthRepository creates a new mock instance.
func NewMockServiceAuthRepository(ctrl *gomock.Controller) *MockServiceAuthRepository {
	mock := &MockServiceAuthRepository{ctrl: ctrl}
	mock.recorder = &MockServiceAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceAuthRepository) EXPECT() *MockServiceAuthRepositoryMockRecorder {
	return m.recorder
}

// CallCreateUser mocks base method.
func (m *MockServiceAuthRepository) CallCreateUser(ctx context.Context, email, username, password string) (uint, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallCreateUser", ctx, email, username, password)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CallCreateUser indicates an expected call of CallCreateUser.
func (mr *MockServiceAuthRepositoryMockRecorder) CallCreateUser(ctx, email, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallCreateUser", reflect.TypeOf((*MockServiceAuthRepository)(nil).CallCreateUser), ctx, email, username, password)
}

// CallLogin mocks base method.
func (m *MockServiceAuthRepository) CallLogin(ctx context.Context, email, password string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallLogin", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CallLogin indicates an expected call of CallLogin.
func (mr *MockServiceAuthRepositoryMockRecorder) CallLogin(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallLogin", reflect.TypeOf((*MockServiceAuthRepository)(nil).CallLogin), ctx, email, password)
}

// CallLogout mocks base method.
func (m *MockServiceAuthRepository) CallLogout(ctx context.Context, refreshToken, accessToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallLogout", ctx, refreshToken, accessToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// CallLogout indicates an expected call of CallLogout.
func (mr *MockServiceAuthRepositoryMockRecorder) CallLogout(ctx, refreshToken, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallLogout", reflect.TypeOf((*MockServiceAuthRepository)(nil).CallLogout), ctx, refreshToken, accessToken)
}

// CallRefresh mocks base method.
func (m *MockServiceAuthRepository) CallRefresh(ctx context.Context, refreshToken string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallRefresh", ctx, refreshToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallRefresh indicates an expected call of CallRefresh.
func (mr *MockServiceAuthRepositoryMockRecorder) CallRefresh(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallRefresh", reflect.TypeOf((*MockServiceAuthRepository)(nil).CallRefresh), ctx, refreshToken)
}

// MockServiceSearchRepository is a mock of ServiceSearchRepository interface.
type MockServiceSearchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockServiceSearchRepositoryMockRecorder
	isgomock struct{}
}

// MockServiceSearchRepositoryMockRecorder is the mock recorder for MockServiceSearchRepository.
type MockServiceSearchRepositoryMockRecorder struct {
	mock *MockServiceSearchRepository
}

// NewMockServiceSearchRepository creates a new mock instance.
func NewMockServiceSearchRepository(ctrl *gomock.Controller) *MockServiceSearchRepository {
	mock := &MockServiceSearchRepository{ctrl: ctrl}
	mock.recorder = &MockServiceSearchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceSearchRepository) EXPECT() *MockServiceSearchRepositoryMockRecorder {
	return m.recorder
}

// CallSearchActors mocks base method.
func (m *MockServiceSearchRepository) CallSearchActors(ctx context.Context, query string, limit, offset uint) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallSearchActors", ctx, query, limit, offset)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallSearchActors indicates an expected call of CallSearchActors.
func (mr *MockServiceSearchRepositoryMockRecorder) CallSearchActors(ctx, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallSearchActors", reflect.TypeOf((*MockServiceSearchRepository)(nil).CallSearchActors), ctx, query, limit, offset)
}

// CallSearchMedia mocks base method.
func (m *MockServiceSearchRepository) CallSearchMedia(ctx context.Context, query string, limit, offset uint) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallSearchMedia", ctx, query, limit, offset)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallSearchMedia indicates an expected call of CallSearchMedia.
func (mr *MockServiceSearchRepositoryMockRecorder) CallSearchMedia(ctx, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallSearchMedia", reflect.TypeOf((*MockServiceSearchRepository)(nil).CallSearchMedia), ctx, query, limit, offset)
}
