// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./mocks/contract_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2025_2_Suzuki_plus_one/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockGetMovieRecommendationsUseCase is a mock of GetMovieRecommendationsUseCase interface.
type MockGetMovieRecommendationsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetMovieRecommendationsUseCaseMockRecorder
	isgomock struct{}
}

// MockGetMovieRecommendationsUseCaseMockRecorder is the mock recorder for MockGetMovieRecommendationsUseCase.
type MockGetMovieRecommendationsUseCaseMockRecorder struct {
	mock *MockGetMovieRecommendationsUseCase
}

// NewMockGetMovieRecommendationsUseCase creates a new mock instance.
func NewMockGetMovieRecommendationsUseCase(ctrl *gomock.Controller) *MockGetMovieRecommendationsUseCase {
	mock := &MockGetMovieRecommendationsUseCase{ctrl: ctrl}
	mock.recorder = &MockGetMovieRecommendationsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetMovieRecommendationsUseCase) EXPECT() *MockGetMovieRecommendationsUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetMovieRecommendationsUseCase) Execute(arg0 context.Context, arg1 dto.GetMovieRecommendationsInput) (dto.GetMovieRecommendationsOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetMovieRecommendationsOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetMovieRecommendationsUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetMovieRecommendationsUseCase)(nil).Execute), arg0, arg1)
}

// MockGetObjectUseCase is a mock of GetObjectUseCase interface.
type MockGetObjectUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetObjectUseCaseMockRecorder
	isgomock struct{}
}

// MockGetObjectUseCaseMockRecorder is the mock recorder for MockGetObjectUseCase.
type MockGetObjectUseCaseMockRecorder struct {
	mock *MockGetObjectUseCase
}

// NewMockGetObjectUseCase creates a new mock instance.
func NewMockGetObjectUseCase(ctrl *gomock.Controller) *MockGetObjectUseCase {
	mock := &MockGetObjectUseCase{ctrl: ctrl}
	mock.recorder = &MockGetObjectUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetObjectUseCase) EXPECT() *MockGetObjectUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetObjectUseCase) Execute(arg0 context.Context, arg1 dto.GetObjectInput) (dto.GetObjectOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetObjectOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetObjectUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetObjectUseCase)(nil).Execute), arg0, arg1)
}

// MockPostAuthSignInUseCase is a mock of PostAuthSignInUseCase interface.
type MockPostAuthSignInUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPostAuthSignInUseCaseMockRecorder
	isgomock struct{}
}

// MockPostAuthSignInUseCaseMockRecorder is the mock recorder for MockPostAuthSignInUseCase.
type MockPostAuthSignInUseCaseMockRecorder struct {
	mock *MockPostAuthSignInUseCase
}

// NewMockPostAuthSignInUseCase creates a new mock instance.
func NewMockPostAuthSignInUseCase(ctrl *gomock.Controller) *MockPostAuthSignInUseCase {
	mock := &MockPostAuthSignInUseCase{ctrl: ctrl}
	mock.recorder = &MockPostAuthSignInUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostAuthSignInUseCase) EXPECT() *MockPostAuthSignInUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockPostAuthSignInUseCase) Execute(arg0 context.Context, arg1 dto.PostAuthSignInInput) (dto.PostAuthSignInOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.PostAuthSignInOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockPostAuthSignInUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockPostAuthSignInUseCase)(nil).Execute), arg0, arg1)
}

// MockGetAuthRefreshUseCase is a mock of GetAuthRefreshUseCase interface.
type MockGetAuthRefreshUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetAuthRefreshUseCaseMockRecorder
	isgomock struct{}
}

// MockGetAuthRefreshUseCaseMockRecorder is the mock recorder for MockGetAuthRefreshUseCase.
type MockGetAuthRefreshUseCaseMockRecorder struct {
	mock *MockGetAuthRefreshUseCase
}

// NewMockGetAuthRefreshUseCase creates a new mock instance.
func NewMockGetAuthRefreshUseCase(ctrl *gomock.Controller) *MockGetAuthRefreshUseCase {
	mock := &MockGetAuthRefreshUseCase{ctrl: ctrl}
	mock.recorder = &MockGetAuthRefreshUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetAuthRefreshUseCase) EXPECT() *MockGetAuthRefreshUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetAuthRefreshUseCase) Execute(arg0 context.Context, arg1 dto.GetAuthRefreshInput) (dto.GetAuthRefreshOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetAuthRefreshOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetAuthRefreshUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetAuthRefreshUseCase)(nil).Execute), arg0, arg1)
}

// MockPostAuthSignUpUseCase is a mock of PostAuthSignUpUseCase interface.
type MockPostAuthSignUpUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPostAuthSignUpUseCaseMockRecorder
	isgomock struct{}
}

// MockPostAuthSignUpUseCaseMockRecorder is the mock recorder for MockPostAuthSignUpUseCase.
type MockPostAuthSignUpUseCaseMockRecorder struct {
	mock *MockPostAuthSignUpUseCase
}

// NewMockPostAuthSignUpUseCase creates a new mock instance.
func NewMockPostAuthSignUpUseCase(ctrl *gomock.Controller) *MockPostAuthSignUpUseCase {
	mock := &MockPostAuthSignUpUseCase{ctrl: ctrl}
	mock.recorder = &MockPostAuthSignUpUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostAuthSignUpUseCase) EXPECT() *MockPostAuthSignUpUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockPostAuthSignUpUseCase) Execute(arg0 context.Context, arg1 dto.PostAuthSignUpInput) (dto.PostAuthSignUpOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.PostAuthSignUpOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockPostAuthSignUpUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockPostAuthSignUpUseCase)(nil).Execute), arg0, arg1)
}

// MockGetAuthSignOutUseCase is a mock of GetAuthSignOutUseCase interface.
type MockGetAuthSignOutUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetAuthSignOutUseCaseMockRecorder
	isgomock struct{}
}

// MockGetAuthSignOutUseCaseMockRecorder is the mock recorder for MockGetAuthSignOutUseCase.
type MockGetAuthSignOutUseCaseMockRecorder struct {
	mock *MockGetAuthSignOutUseCase
}

// NewMockGetAuthSignOutUseCase creates a new mock instance.
func NewMockGetAuthSignOutUseCase(ctrl *gomock.Controller) *MockGetAuthSignOutUseCase {
	mock := &MockGetAuthSignOutUseCase{ctrl: ctrl}
	mock.recorder = &MockGetAuthSignOutUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetAuthSignOutUseCase) EXPECT() *MockGetAuthSignOutUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetAuthSignOutUseCase) Execute(arg0 context.Context, arg1 dto.GetAuthSignOutInput) (dto.GetAuthSignOutOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetAuthSignOutOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetAuthSignOutUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetAuthSignOutUseCase)(nil).Execute), arg0, arg1)
}

// MockGetUserMeUseCase is a mock of GetUserMeUseCase interface.
type MockGetUserMeUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetUserMeUseCaseMockRecorder
	isgomock struct{}
}

// MockGetUserMeUseCaseMockRecorder is the mock recorder for MockGetUserMeUseCase.
type MockGetUserMeUseCaseMockRecorder struct {
	mock *MockGetUserMeUseCase
}

// NewMockGetUserMeUseCase creates a new mock instance.
func NewMockGetUserMeUseCase(ctrl *gomock.Controller) *MockGetUserMeUseCase {
	mock := &MockGetUserMeUseCase{ctrl: ctrl}
	mock.recorder = &MockGetUserMeUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetUserMeUseCase) EXPECT() *MockGetUserMeUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetUserMeUseCase) Execute(arg0 context.Context, arg1 dto.GetUserMeInput) (dto.GetUserMeOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetUserMeOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetUserMeUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetUserMeUseCase)(nil).Execute), arg0, arg1)
}

// MockGetActorUseCase is a mock of GetActorUseCase interface.
type MockGetActorUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetActorUseCaseMockRecorder
	isgomock struct{}
}

// MockGetActorUseCaseMockRecorder is the mock recorder for MockGetActorUseCase.
type MockGetActorUseCaseMockRecorder struct {
	mock *MockGetActorUseCase
}

// NewMockGetActorUseCase creates a new mock instance.
func NewMockGetActorUseCase(ctrl *gomock.Controller) *MockGetActorUseCase {
	mock := &MockGetActorUseCase{ctrl: ctrl}
	mock.recorder = &MockGetActorUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetActorUseCase) EXPECT() *MockGetActorUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetActorUseCase) Execute(arg0 context.Context, arg1 dto.GetActorInput) (dto.GetActorOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetActorOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetActorUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetActorUseCase)(nil).Execute), arg0, arg1)
}

// MockGetMediaUseCase is a mock of GetMediaUseCase interface.
type MockGetMediaUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetMediaUseCaseMockRecorder
	isgomock struct{}
}

// MockGetMediaUseCaseMockRecorder is the mock recorder for MockGetMediaUseCase.
type MockGetMediaUseCaseMockRecorder struct {
	mock *MockGetMediaUseCase
}

// NewMockGetMediaUseCase creates a new mock instance.
func NewMockGetMediaUseCase(ctrl *gomock.Controller) *MockGetMediaUseCase {
	mock := &MockGetMediaUseCase{ctrl: ctrl}
	mock.recorder = &MockGetMediaUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetMediaUseCase) EXPECT() *MockGetMediaUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetMediaUseCase) Execute(arg0 context.Context, arg1 dto.GetMediaInput) (dto.GetMediaOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetMediaOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetMediaUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetMediaUseCase)(nil).Execute), arg0, arg1)
}

// MockGetMediaWatchUseCase is a mock of GetMediaWatchUseCase interface.
type MockGetMediaWatchUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetMediaWatchUseCaseMockRecorder
	isgomock struct{}
}

// MockGetMediaWatchUseCaseMockRecorder is the mock recorder for MockGetMediaWatchUseCase.
type MockGetMediaWatchUseCaseMockRecorder struct {
	mock *MockGetMediaWatchUseCase
}

// NewMockGetMediaWatchUseCase creates a new mock instance.
func NewMockGetMediaWatchUseCase(ctrl *gomock.Controller) *MockGetMediaWatchUseCase {
	mock := &MockGetMediaWatchUseCase{ctrl: ctrl}
	mock.recorder = &MockGetMediaWatchUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetMediaWatchUseCase) EXPECT() *MockGetMediaWatchUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetMediaWatchUseCase) Execute(arg0 context.Context, arg1 dto.GetMediaWatchInput) (dto.GetMediaWatchOutput, *dto.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dto.GetMediaWatchOutput)
	ret1, _ := ret[1].(*dto.Error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetMediaWatchUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetMediaWatchUseCase)(nil).Execute), arg0, arg1)
}
