openapi: "3.0.3"
info:
  title: PopFilms API
  version: "1.0"
  description: |
    This is a main API specification for PopFilms endpoints.

    Note that PopFilms means this very project and not any other one.
servers:
  - url: http://localhost:8080
    description: Local development server
tags:
  - name: page
    description: Endpoints related to updating UI
paths:
  /:
    get:
      tags:
        - page
      summary: Get the main page
      description: Returns PopFilms welcome page
      responses:
        "200":
          description: OK
  /movies:
    get:
      summary: Get all movies page
      tags:
        - page
      responses:
        "200":
          description: A list of movies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Movie"
  /movies/{id}:
    get:
      summary: Get movie personal page
      tags:
        - page
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A single movie
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Movie"
        "404":
          description: Movie not found

components:
  securitySchemes:
    JWT:
      description: JWT bearer token description...
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Movie:
      type: object
      properties:
        id:
          type: string
          example: "123"
        title:
          type: string
          example: "Inception"
        year:
          type: integer
          example: 2010
        genres:
          type: array
          items:
            type: string
          example: ["Sci-Fi", "Thriller"]
